.hlxignore, README.md, package-lock.json, package.json, worker/README.md, worker/src/context.ts, worker/src/handler.ts, worker/src/handler/articleCard.ts, worker/src/handler/articleCards.ts, worker/src/handler/customTagToClassDiv.ts, worker/src/handler/footer.ts, worker/src/handler/fullLayout.ts, worker/src/handler/heroVideo.ts, worker/src/handler/logo-cloud.ts, worker/src/handler/removeInner.ts, worker/src/handler/removeNewline.ts, worker/src/handler/removeOuterTag.ts, worker/src/handler/remover.ts, worker/src/handler/wesee.ts, worker/src/index.ts, worker/src/router.ts, worker/src/routes/content.ts, worker/src/routes/franklin.ts, worker/src/routes/ping.ts, worker/src/types.ts, worker/src/util/error.ts, worker/src/util/index.ts, worker/src/util/response.ts, worker/tsconfig.json, worker/wrangler.toml
Fix #1 
Test URLs:
- https://worker--danaher-ls-aem--hlxsites.hlx.page/
=> feat: worker code and tooling in monorepo

.hlxignore, .husky/pre-commit, .stylelintrc.json, README.md, package-lock.json, package.json, postcss.config.js, scripts/lib-franklin.js, styles/lazy-styles.css, styles/styles.css, styles/tailwind.css, tailwind.config.js
Fix #26 
URL for testing:
- https://feat-tailwind-support--danaher-ls-aem--hlxsites.hlx.page/
=> feat: tailwind support

.github/pull_request_template.md
Test URLs:
- After: https://pr-template--danaher-ls-aem--hlxsites.hlx.page/
=> doc: update preview URLs in PR template

scripts/dom-builder.js
This is a DOM builder that helps to build DOM elements faster. Forked from https://github.com/hlxsites/moleculardevices/blob/main/scripts/dom-helpers.js .
Test URLs:
- After: https://dom-builder--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add DOM builder helper

styles/styles.css, styles/tailwind.css
Relates: #5 
Test URLs:
- After: https://feat-5-headings--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add default heading styles

blocks/hero/hero.css, blocks/hero/hero.js, styles/styles.css, styles/tailwind.css
Fix #9 
Test URLs:
- After: https://feat-9-header--danaher-ls-aem--hlxsites.hlx.live/
=> feat: hero block

.github/workflows/deploy-actions.yaml
Fix #42 
Test URLs:
- After: https://update-env--danaher-ls-aem--hlxsites.hlx.page/
=> [Converter] update environment to Danaher

blocks/hero/hero.js
Test URLs:
- After: https://fix-z-index--danaher-ls-aem--hlxsites.hlx.page/
=> fix: z-index of hero block too high

tools/actions/convert/test/fixtures/en-semantic.html, tools/importer/import.js
Fix #60
Test URLs:
- After: https://fix-60-conv--danaher-ls-aem--hlxsites.hlx.page/
=> [Converter] fix empty section at the end of the doc

blocks/hero/hero.js, styles/styles.css
Test URLs:
- After: https://hero-mobile--danaher-ls-aem--hlxsites.hlx.page/
=> fix: hero heading style

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/en-semantic.html, tools/actions/convert/test/fixtures/footer-semantic.html, tools/importer/import.js
Fix #8 
Test URLs:
- After: https://feat-talk-to-an-expert--danaher-ls-aem--hlxsites.hlx.page/
=> Sticky-Footer -> fetching markup of sticky-footer implementation through import

tools/actions/convert/test/fixtures/footer-semantic.html, tools/importer/import.js
relates #52 
Test URLs:
- After: https://feat-cookies-link--danaher-ls-aem--hlxsites.hlx.page/
=> add special href attribute for manage cookies in footer

blocks/footer/footer.css, blocks/footer/footer.js, styles/styles.css
Fix #55 
Test URLs:
- After: https://fix-footer-sizing--danaher-ls-aem--hlxsites.hlx.page/
=> fix: footer sizing

tools/actions/convert/src/express.js, tools/actions/convert/src/index.js, tools/actions/convert/src/modules/utils/media-utils.js
Fix #61
Test URLs:
- After: https://feat-61-conv--danaher-ls-aem--hlxsites.hlx.page/
=> [Converter] feat: add support to fetch JSON files

paths.yaml
Fix #66 
Test URLs:
- After: https://feat-config--danaher-ls-aem--hlxsites.hlx.page/
=> Add helix config mapping

fragments/wesee.html, scripts/scripts.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://feat-we-see-images--danaher-ls-aem--hlxsites.hlx.live/
=> fix: optimize wesee images and styles

tools/actions/convert/src/index.js
Fix #78 
Test URLs:
- After: https://fix-502-conf--danaher-ls-aem--hlxsites.hlx.page/
=> fix: Converter returns 502 if status code is not 200

blocks/footer/footer.js, styles/styles.css, styles/tailwind.css
Fix #8 
Test URLs:
- After: https://feat-talk-to-an-expert--danaher-ls-aem--hlxsites.hlx.page/
=> sticky-footer layout along with some basic design

blocks/logo-clouds/logo-clouds.js, styles/styles.css, styles/tailwind.css, tools/actions/convert/test/fixtures/en-semantic.html, tools/importer/import.js
Fix #84 
Test URLs:
- After: https://84-fix-logo-cloud-styles--danaher-ls-aem--hlxsites.hlx.page/
=> 84 fix logo cloud styles

blocks/header/header.js, scripts/scripts.js, styles/styles.css
Fix #29 
Test URLs:
- After: https://feat-29-user-quote--danaher-ls-aem--hlxsites.hlx.page/
=> Feat29: user display & quote

blocks/header/header.js, styles/styles.css
Fix #64 
Test URLs:
- After: https://feat-64--danaher-ls-aem--hlxsites.hlx.page/
=> feat: Header megamenu should upon click on dark background

blocks/header/header.js, styles/styles.css
Fix #89 
Test URLs:
- After: https://fix-89--danaher-ls-aem--hlxsites.hlx.page/
=> fix: search Results should redirect to current environment

blocks/header/header.js, scripts/scripts.js, styles/styles.css
Fix #29 
Test URLs:
- After: https://user-cookie--danaher-ls-aem--hlxsites.hlx.page/
=> fix: cookie handling

blocks/logo-clouds/logo-clouds.js, styles/styles.css, styles/tailwind.css
Fix #84 
Test URLs:
- After: https://feat-84-small-style-fix-logo-cloud--danaher-ls-aem--hlxsites.hlx.page/
=> style fix for logo cloud

blocks/header/header.js
Fix #95 
Test URLs:
- After: https://fix-95--danaher-ls-aem--hlxsites.hlx.page/
=> fix: Danaher Logo should be white (safari)

blocks/hero/hero.js
Fix #92 
Test URLs:
- After: https://fix-92--danaher-ls-aem--hlxsites.hlx.page/
=> fix: video playing in background even after closing

README.md, fstab.yaml
Reverts hlxsites/danaher-ls-aem#104
=> Revert "Feat update fstab"

blocks/cards/cards.js
Test URLs:
- After: https://fix-cards--danaher-ls-aem--hlxsites.hlx.page/
=> fix: fix card with external dynmaic media URLs

tools/importer/import.js
Fix #111
Test URLs:
- After: https://fix-card-alt-text--danaher-ls-aem--hlxsites.hlx.page/
=> fix: missing image alt text on cards

blocks/header/header.js
Test URLs:
- After: https://link-name--danaher-ls-aem--hlxsites.hlx.page/
=> fix: LHS check "Links do not have a discernible name"

blocks/cards/cards.css, blocks/cards/cards.js, styles/styles.css, tools/actions/convert/test/fixtures/en-semantic.html
This fixes the card HTML structure to valid markup and use a link tag for the card href instead of JS for better compliance.
Fix #113
Test URLs:
- After: https://fix-cards-html--danaher-ls-aem--hlxsites.hlx.live/
=> fix: card html structure

blocks/footer/footer.js, styles/styles.css, styles/tailwind.css
Fix #103 
Test URLs:
- After: https://bug-sticky-footer-icons--danaher-ls-aem--hlxsites.hlx.page/
=> prepending user icon inside button-group for all except top-button

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Fix #119
Test URLs:
- After: https://fix-119-header-bg--danaher-ls-aem--hlxsites.hlx.page/
=> fix: header bg

tools/actions/convert/test/fixtures/header-semantic.html, tools/importer/import.js
relates #119  
Test URLs:
- After: https://fix-header-section--danaher-ls-aem--hlxsites.hlx.page/
=> fix: remove last section in MegaMenu to remove empty div

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #108 
How-to test/reproduce:
- from web inspector, set image src to an invalid image url or `about:error`
Test URLs:
- After: https://feat-cols-image-load-error--danaher-ls-aem--hlxsites.hlx.page/
=> fix: columns image load error breaks layout

scripts/scripts.js
Fix #[ Phase 0: DataLayer page + user objects #81](https://github.com/hlxsites/danaher-ls-aem/issues/81)
Test URLs:
- After: https://81-datalayer-phase0--danaher-ls-aem--hlxsites.hlx.page/
=> adding phase 0 datalayer

blocks/header/header.js
Fix #118 
Test URLs:
- After: https://fix-118--danaher-ls-aem--hlxsites.hlx.page/
=> fix: Coveo search bar feedback

blocks/cards/cards.js, blocks/footer/footer.js
Fix #132, #130
Test URLs:
- After: https://fix-132-card-link--danaher-ls-aem--hlxsites.hlx.page/
=> fix: card links

package.json, tools/importer/import.js
Test URLs:
- After: https://70-create-events-card-converter--danaher-ls-aem--hlxsites.hlx.page/
=> initial commit for eventcard converter

blocks/header/header.js, scripts/delayed.js
Fix #135
Test URLs:
- After: https://hotfix-135-danaher-config-urls--danaher-ls-aem--hlxsites.hlx.page/
=> fixed config lookups

paths.yaml
Test URLs:
- After: https://header-path--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add headers.json

blocks/footer/footer.js, tools/importer/import.js
Fix #144 
Test URLs:
- After: https://hotfix-144-sticky-footer-utm--danaher-ls-aem--hlxsites.hlx.page/
=> Adding UTM parameter

blocks/footer/footer.js
Fix #130 
Test URLs:
- After: https://bug-discernible-text-footer-icon--danaher-ls-aem--hlxsites.hlx.page/
=> implement aria-label for talk-to-an-expert-icon

tools/importer/import.js
Test URLs:
- After: https://150-add-metadata-props-for-keywords--danaher-ls-aem--hlxsites.hlx.page/
=> Updated metadata for keywords

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/importer/import.js
Fix #140 
Test URLs:
- After: https://140-blog-page-converter-followup--danaher-ls-aem--hlxsites.hlx.page/
=> Blog details page converter - followup

tools/actions/convert/test/fixtures/header-semantic.html, tools/importer/import.js
Fix #176 
Test URLs:
- After: https://176-rebrand-converter-update--danaher-ls-aem--hlxsites.hlx.page/
=> ReBrand updated logo for rebrand

scripts/delayed.js, scripts/scripts.js
Fix #145
Test URLs:
- After: https://hotfix-145-local-storage-parms--danaher-ls-aem--hlxsites.hlx.page/
=> hotfix-145 Added UTM Checks

blocks/blog-hero/blog-hero.css, blocks/blog-hero/blog-hero.js, blocks/popular-articles/popular-articles.css, scripts/scripts.js, styles/styles.css, styles/tailwind.css, templates/blog/blog.css, templates/blog/blog.js
Fix #151 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-cell-painting-making-mark
- After: https://151-blog-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-cell-painting-making-mark
=> feat: implement blog page styles

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/product-semantic.html, tools/actions/convert/test/fixtures/product.html, tools/importer/import.js
Fix # 159
Test URLs:
- After: https://159-implement-converter-product-pages--danaher-ls-aem--hlxsites.hlx.page/
=> 159 implement converter product pages

tools/actions/convert/test/fixtures/header.html, tools/importer/import.js
Fix #186 
Test URLs:
- After: https://186-rebrand-change--danaher-ls-aem--hlxsites.hlx.page/
=> updated converter for new header

tools/actions/convert/test/fixtures/blog-semantic.html, tools/importer/import.js
Fix #157 
Test URLs:
- After: https://157-article-converter-update--danaher-ls-aem--hlxsites.hlx.page/
=> Updated converter for popular articles

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/actions/convert/test/fixtures/blog-hub.html, tools/importer/import.js
Fix #162 
Test URLs:
- After: https://162-converter-blog-news-hub--danaher-ls-aem--hlxsites.hlx.page/
=> Converter changes for blog/news/library

scripts/delayed.js
Test URLs:
- After: https://fix-disable-target--danaher-ls-aem--hlxsites.hlx.page/
=> fix: disable target for performance testing

tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/product-semantic.html, tools/importer/import.js
Fix #185 
Test URLs:
- After: https://185-breadcrumb-convertor--danaher-ls-aem--hlxsites.hlx.page/
=> 185 convertor changes for breadcrumb

helix-query.yaml, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/importer/import.js
Fix #179
Test URLs:
- After: https://fix-blog-date--danaher-ls-aem--hlxsites.hlx.page/
=> fix: align publish date format

tools/importer/import.js
Fix #162
Test URLs:
- After: https://162-blog-hub-conv-update--danaher-ls-aem--hlxsites.hlx.page/
=> fix: improve blog/news hub converter

tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/importer/import.js
Fix #165
Test URLs:
- After: https://162-article-list-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 162-article-list-fix

blocks/recent-articles/recent-articles.css, templates/blog/blog.js, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/blog2.html, tools/importer/import.js
Fix #212 
Test URLs:
- After: https://212-recent-articles-converter--danaher-ls-aem--hlxsites.hlx.page/
=> updated for blog converter

tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/importer/import.js
Fix #212 
Test URLs:
- After: https://212-recent-articles-converter-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 212 Recent articles added as a section

helix-query.yaml, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/importer/import.js
Fix #218 
Test URLs:
- After: https://218-amend-brand-in-article--danaher-ls-aem--hlxsites.hlx.page/
=> 218 Updated brand in meta data

blocks/recent-articles/recent-articles.css, styles/styles.css, tailwind.config.js
Fix #224 
Test URLs:
- After: https://224-purple-50-colour--danaher-ls-aem--hlxsites.hlx.page/
=> Adding Danaher Purple 25

blocks/card-list/card-list.js, styles/styles.css
Fix #230 
Test URLs:
Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
After 1: https://230-blogsnews-hub-accessibility--danaher-ls-aem--hlxsites.hlx.live/us/en/blog
After 2: https://230-blogsnews-hub-accessibility--danaher-ls-aem--hlxsites.hlx.live/us/en/news
=> 230 Accessibility Blog and News Hub

blocks/recent-articles/recent-articles.js, templates/blog/blog.js
Fix #232 
Test URLs:
- After: https://232-articles-not-have-same-page--danaher-ls-aem--hlxsites.hlx.page/
=> 232 Related article issues

fragments/wesee.html, tools/importer/import.js
Fix #236 
Test URLs:
- After: https://236-alt-tags-missing-wesee--danaher-ls-aem--hlxsites.hlx.page/
=> 236 Adding img alt text to wesee

tailwind.config.js
Fix #225 
Test URLs:
- After: https://225-purple-25-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 225 Fix the Danaher Purple 25 Hex

blocks/banner/banner.css, blocks/banner/banner.js, blocks/card-list/card-list.js, blocks/columns/columns.css, package-lock.json, package.json, styles/styles.css, styles/tailwind.css, templates/blog/blog.css, templates/blog/blog.js
Fix #235 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- After: https://layout-fix-blog-banner--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- After Blog 2: https://layout-fix-blog-banner--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/transition-away-from-animal-testing-could-mean-drug-discovery
- Blog page: https://layout-fix-blog-banner--danaher-ls-aem--hlxsites.hlx.live/us/en/blog
=> [Blogs/News] Blog UI Updates to Images #235

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/blog3-semantic.html, tools/actions/convert/test/fixtures/blog3.html, tools/importer/import.js
Fix #222 
Test URLs:
- After: https://222-pdf-viewer-converter--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/enabling-science-at-scale
- After: https://222-pdf-viewer-converter--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/showcases-candidate-selection-tech-bwb
=> 222 Updated converter for embed block

head.html
Fix #190
Test URLs:
- After: https://feat-190-schema--danaher-ls-aem--hlxsites.hlx.live/
=> chore: add ld+json schema

helix-query.yaml
Test URLs:
- After: https://247-mapping-page-meta-title--danaher-ls-aem--hlxsites.hlx.page/
=> 247-mapping-page-meta-title

tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/importer/import.js
Fix #240 
Test URLs:
- After: https://240-blogs-layout-issues-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 240 Updated for layout issues

helix-query.yaml
Test URLs:
- After: https://index-fix--danaher-ls-aem--hlxsites.hlx.page/
=> fix: update index config

helix-query.yaml
Test URLs:
- After: https://index-fix-2--danaher-ls-aem--hlxsites.hlx.page/
=> fix: index fix

helix-query.yaml
Test URLs:
- After: https://index-fix-3--danaher-ls-aem--hlxsites.hlx.page/
=> fix: revert index

styles/styles.css, styles/tailwind.css, templates/blog/blog.css
Fix #254 
Test URLs:
With `<ul>`:
- Blog 1: https://bug-253-list--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/increasing-automation-to-transform-cld-workflows
With `<ol>`:
- Blog 2: https://bug-253-list--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/digital-gold-rush-data-integrity-is-priceless
=> chore: add list styles for blog

blocks/embed/embed.js, scripts/scripts.js
Fix #223
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/enabling-science-at-scale
- After: https://feat-223-pdf-viewer--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/enabling-science-at-scale
=> chore: implement PDF viewer

blocks/blog-hero/blog-hero.js, blocks/breadcrumb/breadcrumb.js, styles/styles.css, templates/blog/blog.js
Fix: #257
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/culture-of-innovation-to-cell-line-development
- After: https://fix-257--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/culture-of-innovation-to-cell-line-development
=> Fix accessibility issues

styles/styles.css
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/helping-labs-comply-with-annex-1-regulation
- After: https://261-blognews-purple-hover--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/helping-labs-comply-with-annex-1-regulation
=> updated purble-50 color

blocks/recent-articles/recent-articles.js
Fix #265 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/news/leica-microsystems-university-of-oxford-collaborate-on-microscopy-center-of-excellence
- After: https://265-recent-article-small-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters
- After: https://265-recent-article-small-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/news/leica-microsystems-university-of-oxford-collab …
=> 265 Tilte check for recent articles

styles/styles.css, templates/blog/blog.css
Fix #262 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/culture-of-innovation-to-cell-line-development
- After: https://262_Button_Style_Fix--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/culture-of-innovation-to-cell-line-development
=> #262 Buttons are not showing correct styling

tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/blog3-semantic.html, tools/actions/convert/test/fixtures/en-semantic.html, tools/actions/convert/test/fixtures/news-semantic.html, tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/actions/convert/test/fixtures/product-semantic.html, tools/importer/import.js
Test URLs:
- After: https://259-canonical-url--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/enabling-science-at-scale
=> 259 Added Canonical URLs

tools/actions/convert/test/fixtures/blog.html, tools/actions/convert/test/fixtures/blog2.html, tools/actions/convert/test/fixtures/news-semantic.html, tools/actions/convert/test/fixtures/news.html, tools/actions/convert/test/fixtures/product.html, tools/importer/import.js
Test URLs:
- After: https://blognews-alttext-on-main-blog-image--danaher-ls-aem--hlxsites.hlx.page/
=> blognews-alttext-on-main-blog-image

blocks/blog-hero/blog-hero.js, blocks/footer/footer.css, blocks/header/header.css, blocks/social-media/social-media.css, styles/styles.css
Fix #271
Test URLs:
- After: https://271-blognews-ux--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/covid-19-dramatically-changes-biopharma-business-ways
- After: https://271-blognews-ux--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
=> 271 blognews ux

styles/styles.css, styles/tailwind.css
Fix #272 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
- After: https://273_TextWrapping--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
=> [Blogs/News] Text wrapping on long text or links #272

tools/actions/convert/src/modules/md2html.js, tools/importer/import.js
Test URLs:
- After: https://converter-sub--danaher-ls-aem--hlxsites.hlx.page/
=> fix: converter to handle <sub> & <sup> tags

blocks/embed/embed.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/enabling-science-at-scale
- After: https://fix-pdf-viewer--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/enabling-science-at-scale
=> fix: pdf viewer

templates/blog/blog.js, tools/actions/convert/test/fixtures/blog.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/blog2.html, tools/actions/convert/test/fixtures/blog3-semantic.html, tools/actions/convert/test/fixtures/blog3.html, tools/actions/convert/test/fixtures/news-semantic.html, tools/actions/convert/test/fixtures/news.html, tools/importer/import.js
Fix #280
Test URLs:
- After: https://280-blognews-seo-canonical--danaher-ls-aem--hlxsites.hlx.page/
- After: https://280-blognews-seo-canonical--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/industrializing-biology-biopharma-4
=> 280 Added aria labels for SEO

blocks/blog-hero/blog-hero.js, blocks/columns/columns.css, styles/styles.css, templates/blog/blog.css
Fix #296 
Test URLs:
- Before: https://lifesciences.danaher.com/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency.html
- https://lifesciences.danaher.com/us/en/blog/fluorescent-dyes.html
- https://lifesciences.danaher.com/us/en/blog/revolutionary-tools-for-streamlining-cell-line-development.html
- After: https://296-bug-in-two-column-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- https://296-bug-in-two-column-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/fluorescent-dyes
- https://296-bug-in-two-column-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/bl …
=> 296 bug in two column layout

blocks/recent-articles/recent-articles.js
Fix #290 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/revolutionizing-drug-discovery-with-organoids
- After: https://290-blognews-bug-view-all--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/revolutionizing-drug-discovery-with-organoids
=> 290 Bugfix for View All in Blogs/News

helix-query.yaml, package.json
Test URLs:
- After: https://query-index-scene7-image-path--danaher-ls-aem--hlxsites.hlx.page/
=> query-index-scene7-image-path

.eslintignore, scripts/lib-franklin.js, scripts/scripts.js
The PR adds the plugin system proposed in https://github.com/adobe/aem-boilerplate/pull/254/.
Test URLs:
- After: https://plugin-system--danaher-ls-aem--hlxsites.hlx.page/
=> feat: add the plugin system to the project

blocks/testimonial/testimonial.css, blocks/testimonial/testimonial.js, styles/styles.css
Fix #275
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
- After: https://275-TestimonialBlockFix--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
=> Fix to the block styling

blocks/callToAction/callToAction.css, tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/actions/convert/test/fixtures/product-category1.html, tools/importer/transformers/callToAction.js
Test URLs:
- After: https://311-converter-update-for-ctasection--danaher-ls-aem--hlxsites.hlx.page/
=> 311-converter-update-for-ctasection

scripts/lib-franklin.js
Remove the block CSS loading as we have combined styles.css
Test URLs:
- After: https://fix-css-loading--danaher-ls-aem--hlxsites.hlx.page/
=> chore: post-fix for css loading

fragments/footer.html
Fix #329 
Test URLs:
- After: https://329-bug-static-footer-link-title--danaher-ls-aem--hlxsites.hlx.page/
=> 329-bug-static-footer-link-title

helix-query.yaml, tools/importer/transformers/metadata.js
Fix #341, #317, #331 
Test URLs:
- After: https://feat-331-product-index--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add index for categories & topics, fix category meta info

.github/workflows/deploy-actions.yaml
Test URLs:
- After: https://category-meta--danaher-ls-aem--hlxsites.hlx.page/
=> chore: update github action to deploy on transformer change

tools/importer/transformers/metadata.js
Test URLs:
- After: https://category-meta-transfrom--danaher-ls-aem--hlxsites.hlx.page/
=> chore: update comment

blocks/card-list/card-list.js, blocks/recent-articles/recent-articles.js, helix-query.yaml
Fix #318
Test URLs:
- After: https://fix-318-article-index--danaher-ls-aem--hlxsites.hlx.live/
=> chore: rename article-index

blocks/card-list/card-list.js, blocks/recent-articles/recent-articles.css, blocks/related-articles/related-articles.js, scripts/scripts.js, styles/styles.css, templates/blog/blog.css, templates/blog/blog.js
Fix #284 
Test URLs:
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/industrializing-biology-biopharma-4
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/the-ai-powered-pixel-classifier
=> 284 related articles UI block

blocks/social-media/social-media.css, styles/styles.css, templates/blog/blog.css
Fix #347 
Test URLs:
- After: https://347-issue-on-social-media--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
=> Updated padding for social media

blocks/card-list/card-list.js, styles/styles.css, templates/blog/blog.css
Fix #349 
Test URLs:
- After: https://349-button-hover-underline-colour--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
=> 349 Button hover underline colour

fragments/footer.html
Fix #354 
Test URLs:
- After: https://354-footer-small-molecules--danaher-ls-aem--hlxsites.hlx.page/
=> 354 Added the Small Molecules link

fragments/footer.html, styles/styles.css
Fix #357 
Test URLs:
- After: https://357-bug-accessibility-footer-button--danaher-ls-aem--hlxsites.hlx.page/
=> 357 Accessibility rating on the footer

helix-query.yaml, package.json
Fix #359
Test URLs:
- After: https://feat-359-category-index--danaher-ls-aem--hlxsites.hlx.page/
=> chore: index banner heading and description

blocks/accordion/accordion.js
Fix #363 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/flow-cytometers
- After: https://363--danaher-ls-aem--hlxsites.hlx.page/us/en/products/flow-cytometers
=> fix: accordion not rendered on some pages

blocks/product-category/product-category.js, helix-query.yaml, styles/styles.css
Fix #350 
Test URLs:
- After: https://350-category-list-xwalk-index--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- After: https://350-category-list-xwalk-index--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes
=> 350 Product category card from crosswalk index

scripts/scripts.js
Test URLs:
- After: https://datalayer-creation-update-dates--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/microscopy-in-virology
=> Datalayer-creation-update-dates

blocks/hero/hero.js
Fix #366
Test URLs:
- After: https://fix-hero-image--danaher-ls-aem--hlxsites.hlx.live/
=> fix: hero img tag

blocks/accordion/accordion.js, blocks/product-category/product-category.js, helix-query.yaml, tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/importer/transformers/accordion.js, tools/importer/transformers/banner.js, tools/importer/transformers/bannerAEM.js
Fix #365 
Test URLs:
- After: https://365-product-category-headings--danaher-ls-aem--hlxsites.hlx.page/
- After: https://365-product-category-headings--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 365 product category headings

blocks/accordion/accordion.js, blocks/banner/banner.css, styles/styles.css
Fix #365 
Test URLs:
- After: https://365-heading-styling-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 365-heading-styling-fix

tools/actions/convert/test/fixtures/product-topic-semantic.html, tools/importer/transformers/containerTakeaway.js
Fix # 373
Test URLs:
- After: https://373-converter-product-topic-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 373-converter-product-topic

tools/actions/convert/test/fixtures/product-topic-semantic.html, tools/importer/transformers/containerTakeaway.js
Fix #373
Test URLs:
- After: https://revert-375-373-converter-product-topic-fix--danaher-ls-aem--hlxsites.hlx.page/
=> Revert "373-converter-product-topic-fix"

blocks/banner/banner.css, blocks/product-category/product-category.js, styles/styles.css, styles/tailwind.css
Fix #372 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page
- After: https://372-product-category-ux--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 377 Product Category UX Changes

tools/importer/transformers/containerTakeaway.js
Fix #373 
Test URLs:
- After: https://373-converter-update-for-product-topic--danaher-ls-aem--hlxsites.hlx.page/
=> 373-converter-update-for-product-topic

tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/actions/convert/test/fixtures/product-topic-semantic.html, tools/importer/transformers/callToAction.js
Test URLs:
- After: https://ctasectionrename--danaher-ls-aem--hlxsites.hlx.page/
=> renaming the block for CTASection

blocks/banner/banner.css, scripts/scripts.js, styles/styles.css
Fix #379 
Test URLs:
- After: https://379-category-ux-page-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 379-category-ux-page-layout

blocks/product-category/product-category.js, tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/importer/transformers/productCategory.js
Fix #382 
Test URLs:
- After: https://382-remove-category-header--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 382-remove-category-header

styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://bug-category-padding--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> Update on padding top and bottom for category page

blocks/category-family/category-family.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/high-performance-liquid-chromatography-systems
- After: https://fix-category-meta--danaher-ls-aem--hlxsites.hlx.page/us/en/products/high-performance-liquid-chromatography-systems
=> fix: category from meta data instead of URL

blocks/category-family/category-family.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/light-microscopes/inverted-light-microscopes
- After: https://fix-category-loading--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/light-microscopes/inverted-light-microscopes
- Test 2: https://fix-category-loading--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges/analytical-ultracentrifuges
=> fix: category URL extraction

blocks/product-category/product-category.js, helix-query.yaml, tools/importer/transformers/metadata.js
Test URLs:
- After: https://bug-product-full-category--danaher-ls-aem--hlxsites.hlx.page/
=> Removed product category and parent category

blocks/product-category/product-category.js
Test URLs:
- After: https://bug-product-full-category-fix--danaher-ls-aem--hlxsites.hlx.page/
=> Bug product full category fix

blocks/category-family/category-family.js, blocks/product-category/product-category.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/products/microscopes
- After: https://fix-categories--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/light-microscopes/stereo-microscopes
- Test 2: https://fix-categories--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> fix: meta data reading

blocks/footer/footer.js, blocks/we-see/we-see.js, scripts/scripts.js, tools/actions/convert/test/fixtures/en-semantic.html, tools/importer/transformers/weSee.js
Fix #174 
Test URLs:
- After: https://174-fragments-link--danaher-ls-aem--hlxsites.hlx.page/
=> feat: remove fragment link from we-see block

templates/topic/topic.js
Fix #395
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/another-thing-about-assay-kits
- After: https://395-topic-page-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/another-thing-about-assay-kits
=> Fix - On the Topic pages the H2

blocks/category-family/category-family.css, styles/styles.css
Fix #[394](https://github.com/hlxsites/danaher-ls-aem/issues/394)
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/light-microscopes/inverted-light-microscopes
- After: https://394-product-category-coveo-card-title--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microscopes/light-microscopes/inverted-light-microscopes
=> 394 - Coveo Card title colours should be black

blocks/social-media/social-media.js
Fix #319
Test URLs:
- After: https://319-social-component-back-button--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/the-ai-powered-pixel-classifier
- After: https://319-social-component-back-button--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/how-are-assay-kits-installed
=> back button functionality to navigate to parent page only

styles/styles.css, styles/tailwind.css
Fix #410
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- After: https://fix-410-heading--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> fix: category heading styles

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/blog6-semantic.html, tools/actions/convert/test/fixtures/blog6.html, tools/importer/transformers/index.js, tools/importer/transformers/table.js, tools/importer/transformers/util.js
=> fix: conversion of tables to correct blocks

blocks/call-to-action/call-to-action.js, styles/styles.css, styles/tailwind.css, templates/topic/topic.css
Fix #397
Test URLs:
- After: https://397-product-category-purple-button--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/how-are-assay-kits-installed
=> button styling on product-category page updated to purple

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/product-topic-semantic.html, tools/actions/convert/test/fixtures/topic-hub-semantic.html, tools/actions/convert/test/fixtures/topic-hub.html, tools/importer/transformers/index.js, tools/importer/transformers/metadata.js, tools/importer/transformers/topicList.js
Fix #335
Test URLs:
- After: https://335--danaher-ls-aem--hlxsites.hlx.page/
=> feat: implement importer code for topic hub page

blocks/category-family/category-family.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/products/mass-spectrometers/integrated-lcms-solutions
- After: https://bug-fix-removed-empty-space--danaher-ls-aem--hlxsites.hlx.live/us/en/products/centrifuges/benchtop-centrifuges
- After: https://bug-fix-removed-empty-space--danaher-ls-aem--hlxsites.hlx.live/us/en/products/mass-spectrometers/integrated-lcms-solutions
- After: https://bug-fix-removed-empty-space--danaher-ls-aem--hlxsites.hlx.live/us/en/products/centrifuges
- After:
=> Removed empty space if the result are 0

tools/actions/convert/test/fixtures/blog-hub-semantic.html, tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog2-semantic.html, tools/actions/convert/test/fixtures/blog3-semantic.html, tools/actions/convert/test/fixtures/blog4-semantic.html, tools/actions/convert/test/fixtures/blog5-semantic.html, tools/actions/convert/test/fixtures/blog6-semantic.html, tools/actions/convert/test/fixtures/news-semantic.html, tools/actions/convert/test/fixtures/news2-semantic.html, tools/actions/convert/test/fixtures/product-category-semantic.html, tools/actions/convert/test/fixtures/product-category1-semantic.html, tools/actions/convert/test/fixtures/product-semantic.html, tools/actions/convert/test/fixtures/product-topic-semantic.html, tools/actions/convert/test/fixtures/topic-hub-semantic.html, tools/importer/transformers/breadcrumb.js
Fix #402 
Test URLs:
- After: https://402-new-section-after-breadcrumb--danaher-ls-aem--hlxsites.hlx.page/
=> 402-Added a new section for the breadcrumb

blocks/breadcrumb/breadcrumb.js, templates/blog/blog.js
Fix #422
Test URLs:
- After: https://fix-422-breadcrumb--danaher-ls-aem--hlxsites.hlx.live/
- Test 2: https://fix-422-breadcrumb--danaher-ls-aem--hlxsites.hlx.live/us/en/products/centrifuges
- Test 3: https://fix-422-breadcrumb--danaher-ls-aem--hlxsites.hlx.live/us/en/blog
- Test 4: https://fix-422-breadcrumb--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/proteomics-analysis-tools
- Test 5: https://fix-422-breadcrumb--danaher-ls-aem--hlxsites.hlx.live/us/en/news/skyland-pims-advances-idbs-mission-accelerate-biopharma
=> chore: update breadcrumb logic for new structure

tools/actions/convert/test/fixtures/blog-semantic.html, tools/actions/convert/test/fixtures/blog.html, tools/importer/transformers/metadata.js
Fix #424
Test URLs:
- After: https://fix-424-datalayer--danaher-ls-aem--hlxsites.hlx.page/
=> fix: datalayer parsing issue

blocks/accordion/accordion.js
Fix #426 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges/benchtop-centrifuges
- After: https://426-bug-bullets-on-the-faq--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges/benchtop-centrifuges
- After: https://426-bug-bullets-on-the-faq--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 426 bug bullets on the faq

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/library-hub-semantic.html, tools/actions/convert/test/fixtures/library-hub.html, tools/importer/transformers/cardList.js, tools/importer/transformers/index.js, tools/importer/transformers/libraryHub.js
Fix #436 
Generate markup for /us/en/library.html
```
<html>
<body>
<header></header>
<main>
<div>
<div class="breadcrumb">
<div>
<div>
<ul>
<li><a href="/us/en/library.html">Knowledge Library Hub</a></li>
</ul>
</div>
</div>
</div>
<hr>
<div class="banner">
<div>
<div>
<h1>Technical Library</h1>
</div>
</div>
</div>
<div class="card-list library">
<div>
<div></div>
</div>
</div>
<div class="metadata">
<div>
<div>Title</div>
<div>Knowledge Library Hub | Danaher Life Sciences</div>
</div>
<div>
<div>canonical</div>
<div><a href="https://lifesciences.danaher.com/us/en/library.html">https://lifesciences.danaher.com/us/en/library.html</a></div>
</div>
<div>
<div>Description</div>
<div>Explore the extensive collection of educational resources for life-sciences research and industrial …
```
=> feat: implement converter for library hub page

blocks/table/table.js, styles/styles.css, templates/blog/blog.css
Fix #412 
Test URLs:
- After: https://412-bug-tables-ux-css--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters
=> [412] => basic table styling

helix-query.yaml
=> chore: add description to index for library cards

tools/actions/convert/test/fixtures/topic-hub-semantic.html, tools/actions/convert/test/fixtures/topic-hub.html, tools/importer/transformers/index.js, tools/importer/transformers/sideNav.js
The side nav content has products or other possibilities so that the block knows which data type to fetch the items.
Fix #442 
Test URLs:
- After: https://442--danaher-ls-aem--hlxsites.hlx.page/
=> feat: implement converter for side nav block

blocks/takeway/takeway.js, styles/styles.css, templates/topic/topic.css
Fix #446 
Test URLs:
- After: https://feat-446-takeaway-ui--danaher-ls-aem--hlxsites.hlx.live/us/en/products/assay-kits/topics/another-test-for-dave
- Test 2: https://feat-446-takeaway-ui--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/the-ai-powered-pixel-classifier
=> feat: implement takeaway as block

tools/importer/transformers/metadata.js
Test URLs:
- After: https://435-add-tag-details-to-page-metadata--danaher-ls-aem--hlxsites.hlx.page/
=> 435-add-tag-details-to-page-metadata

blocks/card-list/applicationCard.js, blocks/card-list/card-list.js
Fix #450 
Test URLs:
- After: https://450-application-hub-page-ui--danaher-ls-aem--hlxsites.hlx.page/us/en/application
=> 450 application hub page UI

helix-query.yaml
=> chore: update title indexing

blocks/header/header.js
Fix #463
Link 1 below on homepage links to Danaher corporate page while all others link to Danaher LS home page like before.
Test URLs:
- Link1 : https://fix-463-header-link--danaher-ls-aem--hlxsites.hlx.live/
- Link2 : https://fix-463-header-link--danaher-ls-aem--hlxsites.hlx.live/us/en/application
=> chore: logo link to Danaher corporate page

styles/styles.css, styles/tailwind.css
Fix #470
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics
- After: https://470--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics
=> chore: ux updates for topic pages

blocks/blog-hero/blog-hero.css, blocks/blog-hero/blog-hero.js, styles/styles.css, styles/tailwind.css, templates/blog/blog.css
Fix #444 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/digital-gold-rush-data-integrity-is-priceless
- After: https://444--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/digital-gold-rush-data-integrity-is-priceless
=> fix: alignment padding issue on blog pages

blocks/call-to-action/call-to-action.js
Test URLs:
- After: 
- https://c2a-button-ui-after-converter-changes--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- https://c2a-button-ui-after-converter-changes--danaher-ls-aem--hlxsites.hlx.page/us/en/library/sequencing
=> c2a-button-ui-after-converter-changes

blocks/topic-list/topic-list.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics
- After: https://sort-topics--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics
=> chore: sort topics based on title alphabetically

fragments/footer.html
Fix #475 
Test URLs:
- After: https://475-bug-cookie-settings-link--danaher-ls-aem--hlxsites.hlx.page/
=> Fixing error in duplicate class tags

blocks/banner/banner.js, blocks/call-to-action/call-to-action.js, blocks/recent-articles/recent-articles.js, styles/styles.css, styles/tailwind.css
Fix #474 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/library/antibodies
- After: https://474-library-recent-articles--danaher-ls-aem--hlxsites.hlx.page/us/en/library/antibodies
=> 474-library-recent-articles

helix-query.yaml
=> chore: add info pages to index

tools/importer/transformers/libraryHub.js
=> chore: update converter for info hub pages

blocks/we-see/we-see.js
Test URLs:
- After: https://fix-wesee--danaher-ls-aem--hlxsites.hlx.page/
=> fix: we see does not load

.gitignore, blocks/call-to-action/call-to-action.js, blocks/recent-articles/recent-articles.js, scripts/lib-franklin.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css, templates/blog/blog.css, templates/library/library.css
Related #468
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/info/what-is-luminescence
- After: https://feat-468-info-template--danaher-ls-aem--hlxsites.hlx.live/us/en/info/what-is-luminescence
=> chore: use library template style for info pages

tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/product1-semantic.html, tools/actions/convert/test/fixtures/product1.html, tools/importer/transformers/carousel.js, tools/importer/transformers/index.js
Test URLs:
- After: https://481-products-converter-for-carousel--danaher-ls-aem--hlxsites.hlx.page/
=> Create converter for carousel

tools/actions/convert/test/fixtures/product-semantic.html, tools/actions/convert/test/fixtures/product1-semantic.html, tools/actions/convert/test/fixtures/product1.html, tools/importer/transformers/index.js, tools/importer/transformers/miniTeaser.js, tools/importer/transformers/twoColumns.js, tools/importer/transformers/util.js, tools/importer/transformers/websiteLinks.js
Fix #485 
Test URLs:
- After: https://485-product-home-two-column--danaher-ls-aem--hlxsites.hlx.page/
=> 485 product home two column

fstab.yaml
Fix #339
Test URLs:
- After: https://update-fstab--danaher-ls-aem--hlxsites.hlx.page/
=> chore: update fstab after new converter is merged

blocks/mini-teasers/mini-teasers.js, styles/styles.css, styles/tailwind.css, templates/application/application.css, tools/actions/convert/test/fixtures/application-detail-converted.html, tools/actions/convert/test/fixtures/application-detail.html, tools/actions/convert/test/fixtures/application-detail1-converted.html, tools/actions/convert/test/fixtures/application-detail1.html, tools/importer/transformers/fullLayoutSection.js
Fix #510
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/application/synthetic-biology
- After: https://510-application-converter-update--danaher-ls-aem--hlxsites.hlx.page/us/en/application/synthetic-biology
- After: https://510-application-converter-update--danaher-ls-aem--hlxsites.hlx.page/us/en/application/elisa
=> 510 Converter update for Full-Layout Section

blocks/cards/cards.js
Fix #512 
Test URLs:
- After: https://512--minor-bug-cards-block--danaher-ls-aem--hlxsites.hlx.page/
- After: https://512--minor-bug-cards-block--danaher-ls-aem--hlxsites.hlx.page/us/en/application/antisense-oligonucleotides
=> 512 Minor bug fix on cards block

styles/styles.css, templates/application/application.css
Test URLs:
- After: https://472-application-layout-changes--danaher-ls-aem--hlxsites.hlx.page/us/en/application/antisense-oligonucleotides
=> Application Page Layout changes

tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product1.html, tools/importer/transformers/index.js, tools/importer/transformers/productCategoryList.js
Fix #519 
Test URLs:
- After: https://519-product-category-list-converter--danaher-ls-aem--hlxsites.hlx.page/
=> 519 Added placeholder for product category list

blocks/call-to-action/call-to-action.js, styles/styles.css
Fix #521 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/application/high-throughput-screening-drug-discovery
- After: https://521-bug-cta-button--danaher-ls-aem--hlxsites.hlx.page/us/en/application/high-throughput-screening-drug-discovery
=> 521 Bug on CTA Button with multiple lines

helix-query.yaml, tools/actions/convert/test/fixtures/product-category2-converted.html, tools/actions/convert/test/fixtures/product-category2.html, tools/importer/transformers/metadata.js
Fix #507 
Test URLs:
- After: https://507-metadata-helix-query-update--danaher-ls-aem--hlxsites.hlx.page/
=> 507 Update on metadata and product index

tools/actions/convert/test/fixtures/product1-converted.html, tools/importer/transformers/carousel.js
Test URLs:
- After: https://carousel-converter-structure-change--danaher-ls-aem--hlxsites.hlx.page/
=> Carousel converter structure change

blocks/hero/hero.js, scripts/scripts.js
Fix #527
Test URLs:
- After: https://feat-527-h1--danaher-ls-aem--hlxsites.hlx.live/
=> feat: better h1 for homepage

helix-query.yaml, tools/actions/convert/test/fixtures/product-category2-converted.html, tools/importer/transformers/metadata.js
Fix #507 
Test URLs:
- After: https://507-metadata-index-fix--danaher-ls-aem--hlxsites.hlx.page/
=> 507-metadata-index-brand-update

styles/styles.css, tools/actions/convert/test/converter.test.js, tools/actions/convert/test/fixtures/application-converted.html, tools/actions/convert/test/fixtures/application-detail-converted.html, tools/actions/convert/test/fixtures/application-detail1-converted.html, tools/actions/convert/test/fixtures/blog-converted.html, tools/actions/convert/test/fixtures/blog-hub-converted.html, tools/actions/convert/test/fixtures/blog2-converted.html, tools/actions/convert/test/fixtures/blog3-converted.html, tools/actions/convert/test/fixtures/blog4-converted.html, tools/actions/convert/test/fixtures/blog6-converted.html, tools/actions/convert/test/fixtures/en-converted.html, tools/actions/convert/test/fixtures/header-converted.html, tools/actions/convert/test/fixtures/library-hub-converted.html, tools/actions/convert/test/fixtures/news-converted.html, tools/actions/convert/test/fixtures/news2-converted.html, tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category1-converted.html, tools/actions/convert/test/fixtures/product-category2-converted.html, tools/actions/convert/test/fixtures/product-converted.html, tools/actions/convert/test/fixtures/product-topic-converted.html, tools/actions/convert/test/fixtures/product1-converted.html
Fix #539
Test URLs:
- After: https://feat-539-tests--danaher-ls-aem--hlxsites.hlx.page/
=> chore: make author tests independent from env

paths.yaml
Fix #547
Test URLs:
- After: https://feat-redirects--danaher-ls-aem--hlxsites.hlx.page/
=> feat: support for redirects

blocks/product-category-list/product-category-list.js, styles/styles.css
Fix #549 
Test URLs:
- After: https://549-ui-product-category-list--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> 549 Updated product category list for opco home

blocks/product-category-list/filter.js, blocks/product-category-list/product-category-list.js
Fix #546 
Test URLs:
- After: https://546-category-list-filter-scroll-down--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
=> 546 category list filter to scroll down

blocks/articles-list/articles-list.js, styles/styles.css
Fix #548 
Test URLs:
- After: https://548-ui-block-for-articles-list--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> UI block update for articles opco home page

blocks/articles-list/articles-list.js, blocks/columns/columns.css, blocks/columns/columns.js, blocks/mini-teasers/mini-teasers.js, blocks/product-category-list/filter.js, blocks/product-category-list/product-category-list.js, blocks/social-feeds/social-feeds.js, scripts/lib-franklin.js, styles/styles.css, styles/tailwind.css, tailwind.config.js, templates/brandHome/brandHome.css
Fix #560 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
- After: https://560-style-update-opco-home-page--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> 560 style update opco home page

blocks/product-category-list/product-category-list.js
Fix #571 
Test URLs:
- After: https://571-feedback-cat-list-3-column--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 571-ux-feedback-category-list-3-column

scripts/lib-franklin.js, tools/actions/convert/test/fixtures/cards-with-icons-converted.html, tools/actions/convert/test/fixtures/cards-with-icons.html, tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product1.html, tools/importer/transformers/index.js, tools/importer/transformers/postProcessSVGIcons.js
Fix #574
Test URLs:
- After: https://feat-574-icons--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> feat: add support from DAM SVG icon loading

blocks/cards/cards.css, styles/styles.css, tailwind.config.js
Fix #572 
Test URLs:
- After: https://572--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> fix: OpCo Cards UX Feedback

blocks/mini-teasers/mini-teasers.js, blocks/product-category-list/product-category-list.js, styles/styles.css
Fix #582 
Test URLs:
- After: https://582-categories-component-headers--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 582-categories-component-headers

blocks/carousel/carousel.js, blocks/columns/columns.css, styles/styles.css, templates/brandHome/brandHome.css
Fix #589 
Test URLs:
- After: https://589-product-opco-left-alignment--danaher-ls-aem--hlxsites.hlx.page/us/en/products
- After: https://589-product-opco-left-alignment--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> 589-product-opco-left-alignment

blocks/product-category-list/product-category-list.js, styles/styles.css
Fix #595 
Test URLs:
- After: https://595-seo-update-ux--danaher-ls-aem--hlxsites.hlx.page/us/en/products
- After: https://595-seo-update-ux--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> 595 seo update ux

blocks/category-family/category-family.js
Fix #590
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/chromatography-columns/lc-columns
- After: https://fix-590--danaher-ls-aem--hlxsites.hlx.page/us/en/products/chromatography-columns/lc-columns
=> fix: fix empty result handling

blocks/articles-list/articles-list.js, blocks/carousel/carousel.js, blocks/mini-teasers/mini-teasers.js, blocks/product-category-list/product-category-list.js, styles/styles.css, styles/tailwind.css, templates/brandHome/brandHome.css
Fix #599 
Test URLs:
- After: https://599-minor-style-updates-on-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
- After: https://599-minor-style-updates-on-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 599 Updated minor styles on product and opco pages

blocks/carousel/carousel.js, styles/styles.css
Fix #599 
Test URLs:
- After: https://599-padding-updates-on-carousels--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 599 Updated padding on carousel on mobiles

styles/styles.css, templates/brandHome/brandHome.css
Fix #602 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/idbs
- After: https://602-product-opco-padding--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/idbs
=> Additional padding on OpCo page

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #606 
Test URLs:
- After: https://606-product-opco-h4-style-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/idbs
=> [Product OpCo] h4 not correctly styled in purple boxes

blocks/carousel/carousel.js
Fix #608 
Test URLs:
- After: https://608-carousel-time--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 608 Updated the Carousel timing

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css
Fix #604 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
- After: https://604-columns-with-borders-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
=> 604 Columns with lines must be more flexible on the content patterns

scripts/lib-franklin.js
Test URLs:
- After: https://rum-sample-rate--danaher-ls-aem--hlxsites.hlx.live/
=> chore: increase sample rate

fstab.yaml, paths.yaml
Related #621
Test URLs:
- After: https://feat-621-metadata-prep--danaher-ls-aem--hlxsites.hlx.page/
=> feat: add support for folders and product metadata

blocks/header/header.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://612-menu-explore-all-button-color--danaher-ls-aem--hlxsites.hlx.page/
=> Menu 'Explore All' button should be btn btn-info

paths.yaml, tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product3-converted.html, tools/importer/transformers/columns.js, tools/importer/transformers/productMenu.js, tools/importer/transformers/util.js
Fix #625 
Test URLs:
- After: https://625-converter-update-product-menu--danaher-ls-aem--hlxsites.hlx.page/
=> 625 converter update product menu

tools/importer/transformers/util.js
Fix #625 
Test URLs:
- After: https://625-minor-fix-replace-url--danaher-ls-aem--hlxsites.hlx.page/
=> 625 Fix changed to replace to slice

tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/importer/transformers/columns.js, tools/importer/transformers/product.js, tools/importer/transformers/util.js
Fix #633 
Test URLs:
- After: https://633-fix-on-feature-section-card--danaher-ls-aem--hlxsites.hlx.page/
=> 633 Converter fix on feature section card

blocks/embed/embed.js, scripts/scripts.js
Fix #629
Test URLs:
- After: https://629-products-vidyard-video--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers
- After: https://629-products-vidyard-video--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica
=> Product Family Page Play Vidyard Video

tools/actions/convert/test/fixtures/product-converted.html, tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/actions/convert/test/fixtures/product3-converted.html, tools/importer/transformers/product.js, tools/importer/transformers/util.js
Fix #637 
Test URLs:
- After: https://637-converter-update-product-page--danaher-ls-aem--hlxsites.hlx.page/
=> 637 Updated converter product detail page

tools/actions/convert/test/fixtures/product-converted.html, tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/actions/convert/test/fixtures/product3-converted.html, tools/importer/transformers/metadata.js, tools/importer/transformers/product.js
Fix #637 
Test URLs:
- After: https://637-minor-converter-update-product--danaher-ls-aem--hlxsites.hlx.page/
=> 637-minor-converter-update-product-page

tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/importer/transformers/util.js
Test URLs:
- After: https://619-minor-converter-update--danaher-ls-aem--hlxsites.hlx.page/
=> 619 added strong to identify title

blocks/recent-articles/recent-articles.js, styles/styles.css, tailwind.config.js, templates/blog/blog.css, templates/library/library.css
Fix #647 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/news/ai-based-rare-event-detection-harnesses-the-capabilities-of-autonomous-confocal-microscopy
- After: https://647--danaher-ls-aem--hlxsites.hlx.page/us/en/news/ai-based-rare-event-detection-harnesses-the-capabilities-of-autonomous-confocal-microscopy
- After: https://647--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/3d-imaging-of-organoid-cultures
- After: https://647--danaher-ls-aem--hlxsites.hlx.page/us/en/library/plasmid-construct
=> 652 fix: high CLS from recent articles

blocks/recent-articles/recent-articles.js
Fix #649 
Test URLs:
- After: https://649-seo-contrast--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/life-sciences-firm-cellesce-exits
=> 649 SEO Update Colour Contrast

tools/actions/convert/test/fixtures/product-converted.html, tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/actions/convert/test/fixtures/product3-converted.html, tools/importer/transformers/product.js, tools/importer/transformers/util.js
Fix #654 
Test URLs:
- After: https://654-converter-update-for-citations--danaher-ls-aem--hlxsites.hlx.page/
=> 654 Updated converter for citations

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js, styles/styles.css
Test URLs:
- After: https://fix-product-cls--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> fix: low LHS on products sku pages

blocks/product-overview/product-overview.css, blocks/product-overview/product-overview.js, styles/styles.css, styles/tailwind.css
Fix #666 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges#overview
- After: https://666-product-coveo-overview--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges#overview
=> updated for product overview block

blocks/product-hero/product-hero.css, styles/styles.css
Fix #669 
Test URLs:
- After: https://669-product-styling--danaher-ls-aem--hlxsites.hlx.live/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> 669 Hero CSS Changes for LHS and UX

blocks/product-hero/product-hero.js, styles/styles.css
Fix #166 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/m80-ergonomic-stereo-microscopes-for-inspection-with-removable-integrated-camera
- After: https://166-extnt-product-detail-for-bundle--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/m80-ergonomic-stereo-microscopes-for-inspection-with-removable-integrated-camera
=> 166 Added Bundle Information to Product Hero

blocks/page-tabs/page-tabs.css, blocks/page-tabs/page-tabs.js, blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js, styles/styles.css, styles/tailwind.css, templates/productDetail/productDetail.js
Fix #668 and #680
Test URLs:
- After: https://668-prod-tab-block-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> Product Tab block layout and hover

blocks/product-menu/product-menu.css, blocks/product-menu/product-menu.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css
Fix #660 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biophase-8800-capillary-electrophoresis-systems
- After: https://660--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biophase-8800-capillary-electrophoresis-systems#overview
=> feat: implement product menu with embedded fragments

blocks/page-tabs/page-tabs.js, blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://fix-product-tbt--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> improve LHS on product pages

blocks/page-tabs/page-tabs.js
Fix #682 
Test URLs:
- After: https://682-page-tabs-on-mobile--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biomek-ngenius-next-generation-library-prep-systems
=> 682 page tabs on mobile

blocks/page-tabs/page-tabs.js, blocks/product-children/product-children.js, blocks/product-children/product-tile.js, blocks/product-parts/product-parts.js, blocks/product-resources/product-resources.js
Fix #691 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/m80-routine-stereo-microscopes
- After: https://691-product-product-tile-fixes--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/m80-routine-stereo-microscopes
=> 691 product product tile fixes

scripts/scripts.js, templates/productDetail/productDetail.js
Fix #701 
Test URLs:
- After: https://701-host-name-in-config--danaher-ls-aem--hlxsites.hlx.page/
=> Product Detail Page - Add Host Name in Danaher Config

scripts/scripts.js
Fix #687
Test URLs:
- After: https://687-link-new-same-window--danaher-ls-aem--hlxsites.hlx.page/
=> 687 update external links to open in new tab

scripts/scripts.js
Test URLs:
- Test 1: https://image-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/m80-stereomicroscope-camera-monitor-bundle
- Test 2: https://image-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/2026335-molecular-devices
- Test 3: https://image-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> chore: fix default image loading

blocks/carousel/carousel.js
Fix #703 
Test URLs:
- After: https://703-rfq-button-carousel-not-work--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> 703 Added RFQ functionality for carousel

blocks/category-family/category-family.js, blocks/product-children/product-children.js, blocks/product-resources/product-resources.js
Fix #713 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biozen-biologics-lc-columns
- After: https://713-product-items-limit--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biozen-biologics-lc-columns
=> 713 Updated to limit 20 before pagination

blocks/category-family/category-family.js
Fix #713 
Test URLs:
- After: https://713-product-items-limit--danaher-ls-aem--hlxsites.hlx.page/
=> 713 reverting back to 48 as no pagination on family pages.

tools/actions/convert/test/fixtures/product1-converted.html, tools/actions/convert/test/fixtures/product2-converted.html, tools/actions/convert/test/fixtures/product4-converted.html, tools/importer/transformers/metadata.js
Fix #711
Test URLs:
- After: https://meta-img-711--danaher-ls-aem--hlxsites.hlx.page/
=> fix: image metadata extraction

styles/styles.css, styles/tailwind.css
Fix #721 
Test URLs:
- After: https://721-bug-accessibility-icon--danaher-ls-aem--hlxsites.hlx.page/
=> 721 Updated accessibility icon style

blocks/page-tabs/page-tabs.js
Fix #719 
Test URLs:
- After: https://719-shown-hidden-tabs-mobile--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/qpix-microbial-colony-pickers
=> JumpMenu drop down showing tabs that should be hidden

blocks/product-hero/product-hero.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/intabio-zt-systems
- Test 1: https://img-test--danaher-ls-aem--hlxsites.hlx.live/us/en/products/family/intabio-zt-systems
- Test 2: https://img-test--danaher-ls-aem--hlxsites.hlx.live/us/en/products/family/optima-max-tl-ultracentrifuges
- Test 3: https://img-test--danaher-ls-aem--hlxsites.hlx.live/us/en/products/family/pclamp-11-software-suite
=> chore: improve product LCP block & image loading

tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions.html, tools/importer/transformers/index.js, tools/importer/transformers/pageJumpMenu.js
Fix #717 
Test URLs:
- After: https://717-converter-for-page-jump-menu--danaher-ls-aem--hlxsites.hlx.page/
=> 717 [Solutions] Updated for page jump menu 

blocks/page-tabs/page-tabs.js, blocks/product-resources/product-resources.js, styles/styles.css, styles/tailwind.css
Fix #720 
Test URLs:
- After: https://720-accessibility-issue-on-lhs--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biozen-biologics-lc-columns
=> 720 Jump Menu Accessibility issue on LHS

blocks/banner/banner.js
Fix #748 
Test URLs:
- After: https://748-banner-styles-broken--danaher-ls-aem--hlxsites.hlx.page/us/en/library
- After: https://748-banner-styles-broken--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
- After: https://748-banner-styles-broken--danaher-ls-aem--hlxsites.hlx.page/us/en/news
- After: https://748-banner-styles-broken--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> [Banner] Styles broken

tools/actions/convert/test/fixtures/blog-topics-template-converted.html, tools/importer/transformers/cardList.js
Related #677
Test URLs:
- After: https://tag-pages--danaher-ls-aem--hlxsites.hlx.live/
=> add missing block option to indicated cards are filtered

tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions.html, tools/importer/transformers/columns.js, tools/importer/transformers/util.js
Fix #755 
Test URLs:
- After: https://755-quick-fix-in-column-for-button--danaher-ls-aem--hlxsites.hlx.page/
=> 755 quick fix in column for button

blocks/page-tabs/page-tabs.js, blocks/product-children/product-children.js, blocks/product-hero/product-hero.js, blocks/product-overview/product-overview.js, blocks/product-parts/product-parts.js, blocks/product-resources/product-resources.js, blocks/product-specifications/product-specifications.js, scripts/scripts.js, templates/productDetail/productDetail.js
Fix #735 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/pclamp-11-software-suite
- After: https://735-breadcrumbs-dynamic-product--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/pclamp-11-software-suite
=> 735 Updated breadcrumb for dynamic products

blocks/carousel/carousel.js
Fix #758 
Test URLs:
- After: https://758-carousel-btn-broken--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> [Bug] carousel 'View Product' button broken

paths.yaml
Test URLs:
- After: https://metadata--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add metadata-articles

blocks/card-list/card-list.js, tools/importer/transformers/cardList.js
Fix #677
Test URLs:
Test 1: https://topics-pages-fix--danaher-ls-aem--hlxsites.hlx.live/us/en/blog
Test 2: https://topics-pages-fix--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/topics/mrna
Test 3: https://topics-pages-fix--danaher-ls-aem--hlxsites.hlx.live/us/en/blog/topics/next-gen-therapeutics
=> topic pages: fix urls & banner

paths.yaml
Test URLs:
- After: https://753-update-in-paths-yaml--danaher-ls-aem--hlxsites.hlx.page/
=> 753 Updated the xf path in yaml

blocks/header/header.js, blocks/page-tabs/page-tabs.js, blocks/product-children/product-children.js, blocks/product-hero/product-hero.js, blocks/product-overview/product-overview.js, blocks/product-parts/product-parts.js, blocks/product-resources/product-resources.js, blocks/product-specifications/product-specifications.js, scripts/commerce.js, scripts/scripts.js, styles/styles.css, templates/productDetail/productDetail.js
Fix #763 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/pclamp-11-software-suite#products
- After: https://763-minor-fix-for-breadcrumb--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/pclamp-11-software-suite#products
- After: https://763-minor-fix-for-breadcrumb--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
- After: https://763-minor-fix-for-breadcrumb--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/genepix-microarray-systems
=> 763 minor fix and refactor for product breadcrumb

blocks/category-family/category-family.js, blocks/product-resources/product-resources.js
Fix #759
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microbioreactors
- After: https://759-coveo-family-line-clamp-title--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microbioreactors
=> clipping text line limit to 3 for title only

paths.json
Test URLs:
- After: https://paths-json--danaher-ls-aem--hlxsites.hlx.page/
=> chore: add paths.json

tools/actions/convert/test/fixtures/solutions-converted.html, tools/importer/transformers/workflowTabs.js
Test URLs:
- After: https://753-converter-update-for-XF--danaher-ls-aem--hlxsites.hlx.page/
=> 753 Quick update on fragment path

tools/actions/convert/test/fixtures/solutions-converted.html, tools/importer/transformers/download.js
Fix #776 
Test URLs:
- After: https://776-update-download-comp--danaher-ls-aem--hlxsites.hlx.page/
=> Converter for download component

blocks/cards/cards.js
Fix #767 
Test URLs:
- After: https://767-product-opco-cards-clickable--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> opco-card clickable

styles/styles.css, styles/tailwind.css
Fix #774 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers
- After: https://774-category-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers
- After https://774-category-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/products/clone-screening-systems
=> 774 Category Page Paragraph Spacing

tools/actions/convert/test/fixtures/workflow-carousel-converted.html, tools/actions/convert/test/fixtures/workflow-carousel.html, tools/actions/convert/test/fixtures/workflow-tab-script-converted.html, tools/actions/convert/test/fixtures/workflow-tab-script.html, tools/importer/transformers/embedScript.js, tools/importer/transformers/index.js, tools/importer/transformers/workflowCarousel.js
Fix #780 
Test URLs:
- After: https://780-converter-for-workflow-carousels--danaher-ls-aem--hlxsites.hlx.page/
=> 780 Converter for workflow carousel

styles/styles.css, styles/tailwind.css
Fix #774 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers
- After: https://774-category-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers
- After: https://774-category-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/products/capillary-electrophoresis-systems
=> 774 Category Spacing - Amended to fix issue with top padding

blocks/page-jump-menu/page-jump-menu.js, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions-process-steps-converted.html, tools/actions/convert/test/fixtures/talk-to-expert-converted.html, tools/importer/transformers/pageJumpMenu.js
Test URLs:
- After: https://fix-converter-page-jum-menu--danaher-ls-aem--hlxsites.hlx.page/
=> Fix on converter for page jump menu

tools/actions/convert/test/fixtures/blog3-converted.html, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/talk-to-expert-converted.html, tools/importer/transformers/embedScript.js
Fix #797 
Test URLs:
- After: https://797-converter-marketo-form--danaher-ls-aem--hlxsites.hlx.page/
=> 797 [Solutions] Converter updates for MarketoForm

tools/actions/convert/test/fixtures/blog3-converted.html, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/talk-to-expert-converted.html, tools/importer/transformers/embedScript.js
Fix #812 
Test URLs:
- After: https://812-converter-marketo-form--danaher-ls-aem--hlxsites.hlx.page/
=> Converter updates to Marketo Form

404.html, scripts/commerce.js, templates/productDetail/productDetail.js
Fix #811 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica1
- After: https://fix-product-not-found-404--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica1
=> Fix Updated product 404 page

blocks/columns/columns.css, styles/styles.css
Fix #809 
Test URLs:
- After: https://809-white-colour-to-svgs--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/spectramax-id3-id5-series-microplate-readers
=> Add White colour to SVGs

tools/actions/convert/test/fixtures/solutions-process-steps-converted.html, tools/importer/transformers/timeline.js
Test URLs:
- After: https://minor-fix-timeline-converter--danaher-ls-aem--hlxsites.hlx.page/
=> Minor fix on timeline converter

tools/actions/convert/test/fixtures/solutions-process-steps-converted.html, tools/importer/transformers/timeline.js
Test URLs:
- After: https://fix-seo-timeline-converter--danaher-ls-aem--hlxsites.hlx.page/
=> Updated for improve seo score

scripts/commerce.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica-1234
- After: https://fix-product-404-page--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica-1234
=> Fix for product 404 page

scripts/commerce.js
Test URLs:
- After: https://fix-product-404--danaher-ls-aem--hlxsites.hlx.page/
=> Fixed product 404 page

blocks/product-hero/product-hero.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-xe-ultracentrifuges
- After: https://823-product-hero-width--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-xe-ultracentrifuges
=> 823 Updated to give hero text 100% width

scripts/schema.js, templates/productDetail/productDetail.js
Fix #297 
Test URLs:
- After: https://297-product-schema--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
- After: https://297-product-schema--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family//us/en/products/family/optima-xe-ultracentrifuges
- After: https://297-product-schema--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/vi-cell-blu-cell-viability-analyzers
- After: https://297-product-schema--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/c09736-beckman-coulter-life …
=> 297 Product Schema Org

blocks/page-jump-menu/page-jump-menu.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://fix-timeline-css--danaher-ls-aem--hlxsites.hlx.page/
=> Added timeline CSS

styles/styles.css, styles/tailwind.css
Fix #837 
Test URLs:
- After: https://837-rebrand-footer-hover--danaher-ls-aem--hlxsites.hlx.page/
=> 837 Sticky Footer Hover Colour Change

scripts/schema.js
Fix #383 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/vi-cell-blu-cell-viability-analyzers
- After: https://838-schema-aem-titles--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/vi-cell-blu-cell-viability-analyzers
=> 838 Schema Postfix Danaher title removal

tools/actions/convert/test/fixtures/product-home-converted.html, tools/actions/convert/test/fixtures/product-home.html, tools/actions/convert/test/fixtures/solution-products-converted.html, tools/actions/convert/test/fixtures/solution-products.html, tools/importer/transformers/productCategoryList.js
Test URLs:
- After: https://fix-converter-for-wf-products--danaher-ls-aem--hlxsites.hlx.page/
=> Updated converter for solutions product pages

blocks/product-category/product-category.js, scripts/schema.js
Fix #833 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- After: https://833-add-schema-for-category-lists--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 833 Added schema changes for product category list

scripts/commerce.js
Fix #816 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica
- After: https://816-impl-cf-api-in-product--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica
=> Updated CF API Implementation for product

scripts/schema.js
Fix #848 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/echo-ms-systems
- After: https://848-schema-update--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/echo-ms-systems
- After: https://848-schema-update--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 848 Schema Update for Category Title, Seller and Manufacturer

blocks/cards/cards.css, blocks/cards/cards.js, styles/styles.css, styles/tailwind.css
Reverts hlxsites/danaher-ls-aem#853
https://revert-853-852-remove-block-css-cards--danaher-ls-aem--hlxsites.hlx.page/
=> Revert "852 [SEO] Remove block css from cards"

blocks/product-hero/product-hero.js
Fix #794 
Test URLs:
- After: https://amend-h1-tag-product-title--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-auc-analytical-ultracentrifuge
=> Amended h1 tag to product title

blocks/product-card/product-card.js, scripts/commerce.js
Fix #879 
Test URLs:
- After: https://879-prod-list-clickevent--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> 879 Product List clickEvent issue on solutions page

helix-query.yaml, tools/actions/convert/test/fixtures/product-home.html, tools/actions/convert/test/fixtures/product-opco-home.html, tools/actions/convert/test/fixtures/solution-process-step-detail-converted.html, tools/actions/convert/test/fixtures/solution-process-step-detail.html, tools/importer/transformers/metadata.js, tools/importer/transformers/productCategoryList.js
Fix #876 
Test URLs:
- After: https://converter-update-solutions--danaher-ls-aem--hlxsites.hlx.page/
=> Converter update for process steps page in solutions

tools/actions/convert/test/fixtures/product-recommendations-converted.html, tools/actions/convert/test/fixtures/product-recommendations.html, tools/importer/transformers/product.js
Fix #874 
Test URLs:
- After: https://874-converter-prod-recomns--danaher-ls-aem--hlxsites.hlx.page/
=> 874 [Product] Converter updates Product Recommendations

scripts/commerce.js
Test URLs:
- After: https://883-product-list-not-found--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> 883 [Solutions] Removed page not found block

scripts/scripts.js
Fix #875 
Test URLs:
- After: https://875-favicon--danaher-ls-aem--hlxsites.hlx.page/
=> 875 Add Favicon

blocks/product-hero/product-hero.js
Test URLs:
- After: https://fix-product-hero--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cytoflex-srt-benchtop-cell-sorters
- After:  https://fix-product-hero--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> Fix for product hero h1 tag

scripts/delayed.js
Test URLs:
- After: https://fix-product-hero--danaher-ls-aem--hlxsites.hlx.page/
=> fixed in delayed JS

helix-query.yaml
Test URLs:
- After: https://fix-solution-query-index--danaher-ls-aem--hlxsites.hlx.page/
=> Fix: Updated the solution index

tools/importer/transformers/metadata.js
Test URLs:
- After: https://fix-solution-metadata--danaher-ls-aem--hlxsites.hlx.page/
=> Updated solution metadata

helix-query.yaml
Test URLs:
- After: https://fix-solution-index--danaher-ls-aem--hlxsites.hlx.page/
=> Reading h1 from body instead of main

helix-query.yaml
Reverts hlxsites/danaher-ls-aem#893
=> Revert "Reading h1 from body instead of main"

helix-query.yaml
Test URLs:
- After: https://fix-solution-index--danaher-ls-aem--hlxsites.hlx.page/
=> Added OR condition for h1

styles/styles.css, styles/tailwind.css
Fix #895 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/streamlining-plasmid-library-development
- After: https://895-underline-links--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/streamlining-plasmid-library-development
=> 895 ReBrand Link Styling

blocks/card-list/articleCard.js, blocks/card-list/card-list.js, styles/styles.css
Fix #867 
Test URLs:
- After: https://867-rebrand-cards-for-blognews--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
- After: https://867-rebrand-cards-for-blognews--danaher-ls-aem--hlxsites.hlx.page/us/en/news
=> 867 rebrand-cards-for-blognews

scripts/commerce.js
Fix #881 
Test URLs:
- After: https://881-update-search-payload--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> 881 [Solutions] Update Search Payload

scripts/delayed.js
Fix #863
Test URLs:
- After: https://863-bug-404-on-product-pages--danaher-ls-aem--hlxsites.hlx.page/
=> Fix for 404 page on product detail

blocks/page-jump-menu/page-jump-menu.css, blocks/page-jump-menu/page-jump-menu.js, blocks/side-nav/side-nav.js, scripts/commerce.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css, templates/processstep/processstep.css, templates/processstep/processstep.js
Fix #869 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps/vector-construction
- After: https://feat-solution-process-step-ui--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps/vector-construction
=> 869 Solution process step UI

blocks/side-nav/side-nav.js, styles/styles.css, templates/processstep/processstep.css
Test URLs:
- After: https://fix-solution-layout--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps/vector-construction
=> Updated layout for solution page

blocks/product-category/product-category.js
Fix #865 
Test URLs:
- After: https://865-no-schema-items-null--danaher-ls-aem--hlxsites.hlx.page/
=> 865 Updated item-list schema script call if there no product

styles/coveo-atomic.css, styles/styles.css, tools/actions/convert/test/fixtures/en.html
Fix #905 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges/benchtop-centrifuges
- After: https://905-rebrand-coveo--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges/benchtop-centrifuges
=> 905 Coveo ReBrand Font

scripts/commerce.js
Fix #904 
Test URLs:
- After: https://904-remove-local-cache-no-product--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-auc-analytical-ultracentrifuge
- After: https://904-remove-local-cache-no-product--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-auc-analytical-ultracentrifuge-ravi
=> 904 Removing local storage if there no product found

tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category.html, tools/importer/transformers/ctaText.js, tools/importer/transformers/index.js
Fix #909 
Test URLs:
- After: https://909-converter-cta-text--danaher-ls-aem--hlxsites.hlx.page/
=> 909 Converter update for CTA Text

tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category.html, tools/importer/transformers/callToActionText.js, tools/importer/transformers/index.js
Fix #914 
Test URLs:
- After: https://914-converter-cta-text--danaher-ls-aem--hlxsites.hlx.page/
=> 914 Converter change for CTA Text

tools/importer/transformers/callToActionText.js
Fix #916 
Test URLs:
- After: https://916-rename-cta-text--danaher-ls-aem--hlxsites.hlx.page/
=> 916 Converter update rename CTA Text

tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category.html, tools/importer/transformers/callToActionText.js
Test URLs:
- After: https://converter-cta-text--danaher-ls-aem--hlxsites.hlx.page/
=> Converter update for cta text

tools/actions/convert/test/fixtures/product-category-converted.html, tools/importer/transformers/callToActionText.js
Test URLs:
- After: https://921-update-cta-text--danaher-ls-aem--hlxsites.hlx.page/
=> 921-update-cta-text

tools/actions/convert/test/fixtures/cards-with-icons.html, tools/actions/convert/test/fixtures/new-home-page-converted.html, tools/actions/convert/test/fixtures/new-home-page.html, tools/actions/convert/test/fixtures/product-home.html, tools/importer/transformers/accordion.js, tools/importer/transformers/miniTeaser.js
Fix #911 
Test URLs:
- After: https://911-converter-update-mini-teaser--danaher-ls-aem--hlxsites.hlx.page/
=> 911 converter update mini teaser

tools/actions/convert/test/fixtures/new-home-page-converted.html, tools/actions/convert/test/fixtures/product-opco-home-converted.html, tools/actions/convert/test/fixtures/product-opco-home.html, tools/importer/transformers/opcoHomeArticlesList.js
Fix #924 
Test URLs:
- After: https://924-converter-articlesopcohome--danaher-ls-aem--hlxsites.hlx.page/
=> 924 [Homepage] Converter updates for Articles Opco Home

blocks/articles-list/articles-list.js
Fix #926 
Test URLs:
- After: https://926-ui-articles-opco-home--danaher-ls-aem--hlxsites.hlx.page/us/en/new-homepage
- After: https://926-ui-articles-opco-home--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 926 [Homepage] UI for Articles Opco Home

blocks/articles-list/articles-list.js
Fix #929 
Test URLs:
- After: https://929-brand-articles-opco-home--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/leica
=> 929 [Homepage] Remove brand from Articles Opco Home

blocks/call-to-action/call-to-action.js
Fix #931 
Test URLs:
- After: https://931-padding-cta-text--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> 931 [Block] Add padding top to CTA Text

blocks/call-to-action/call-to-action.js
Fix #931 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- After: https://931-padding-cta-text--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> CTA Padding - slight reduction

blocks/mini-teasers/mini-teasers.js, styles/styles.css, tools/actions/convert/test/fixtures/new-home-page-converted.html, tools/importer/transformers/accordion.js
Test URLs:
- After: https://fix-accordion-converter-update--danaher-ls-aem--hlxsites.hlx.page/
=> Updated accordion converter for image

scripts/scripts.js
Fix #936 
Test URLs:
- After: https://936-datalayer-page-level-and-type--danaher-ls-aem--hlxsites.hlx.page/
=> 936 adding datalayer page type + level logic

blocks/page-jump-menu/page-jump-menu.js, blocks/page-tabs/page-tabs.js
Fix #942 
Test URLs:
- After: https://942-overlay-zIndex--danaher-ls-aem--hlxsites.hlx.page/
=> [ 942 ] -> Z-Index issue between jump-menu, page-tabs and sticky-footer

blocks/carousel/carousel.js, styles/styles.css
Fix #940 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://940-carousel-next-and-previous-button--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
=> [ 940 ] -> Carousel Next & Previous button alignment and functionality

scripts/delayed.js
Fix #950 
Test URLs:
- After: https://950-coveo-pageview-onetrust--danaher-ls-aem--hlxsites.hlx.page/
=> adding conditional for onetrust for coveo view event

blocks/call-to-action/call-to-action.js, blocks/workflow-carousel/workflow-carousel.js, scripts/scripts.js
Test URLs:
- After: https://fix-solution-page--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://fix-solution-page--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
=> Fixed two col section for solution page

blocks/accordion/accordion.js
Test URLs:
- After: https://fix-accordion-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://fix-accordion-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges
- After: https://fix-accordion-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/new-homepage
=> Added condition to display image

scripts/scripts.js
Fix #958 
Test URLs:
- After: https://958-target-add-regex--danaher-ls-aem--hlxsites.hlx.page/
=> 958 Adobe Target Implementation - Regex page validation

scripts/commerce.js
Fix #964 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
- After: https://964-solutions-coveo-payload--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> 964 reducing coveo response object size

blocks/carousel/carousel.js
Fix #973 
Test URLs:
- After: https://973-errors-carousel--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy
- After: https://973-errors-carousel--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs
=> 973 Carousel console errors fix.

blocks/marketo-form/marketo-form.js, blocks/timeline/timeline.js, scripts/commerce.js, styles/styles.css
Fix #975 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/pdna-synthesis/products
- After: https://975-products-not-appearing-pdna--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/pdna-synthesis/products
- After: https://975-products-not-appearing-pdna--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/pdna-synthesis/process-steps/plasmid-vector-component-selection-design
=> 975 Fixed product page for solutions

blocks/marketo-form/marketo-form.js, blocks/workflow-carousel/workflow-carousel.js, scripts/scripts.js, styles/styles.css, styles/tailwind.css
Fix #957 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://957-solutions-mobile-view--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
=> 957 Solutions page Mobile View Responsiveness

blocks/blog-hero/blog-hero.js, blocks/product-hero/product-hero.css, styles/styles.css, styles/tailwind.css, tailwind.config.js
Fix #972 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy/mrna-development-manufacturing
- After: https://972-bug-h1-solutions--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy/mrna-development-manufacturing
- After: https://972-bug-h1-solutions--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> 972 Update H1 Styling

blocks/timeline/timeline.js
Test URLs:
- After: https://fix-timeline-munu--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps
=> Updated styles for timeline menu

blocks/product-card/product-card.js, styles/styles.css, styles/tailwind.css
Fix #986 
Test URLs:
- After: https://986-reduce-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy/mrna-development-manufacturing/products
- After: https://986-reduce-spacing--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> 986 [UX] Solution Products - Reduce the spacing

scripts/delayed.js
Fix #960 
Test URLs:
- After: https://960-coveo-update-to-page-event--danaher-ls-aem--hlxsites.hlx.page/
=> 960 Coveo update to page event

tools/actions/convert/test/fixtures/blog-topics-template-converted.html, tools/actions/convert/test/fixtures/blog-topics-template.html, tools/importer/transformers/cardList.js, tools/importer/transformers/index.js, tools/importer/transformers/infoHub.js
Fix #1015 
Test URLs:
- After: https://1015-converter-update-library--danaher-ls-aem--hlxsites.hlx.page/
=> 1015 [Hubs] Converter update for Library Hub

blocks/accordion/accordion.js, blocks/header/header.js, icons/arrow-left.svg, icons/arrow-right.svg, icons/chevron-down.svg, icons/menu.svg, icons/minus.svg, icons/x.svg
Test URLs:
- After: https://951-animation-to-accordion--danaher-ls-aem--hlxsites.hlx.page/
=> 951 Added icon references from the code base

blocks/header/header-dev.css, blocks/header/header.css, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://fix-header-height-style--danaher-ls-aem--hlxsites.hlx.page/
=> Fix header height from Style CSS

blocks/cards/cards.js, styles/styles.css
Fix #1058 
Test URLs:
- After: https://1058-remove-cardscss--danaher-ls-aem--hlxsites.hlx.page/
=> 1058 CSS changes cards.js

blocks/cards/cards.js, styles/styles.css
Fix #1063
Test URLs:
- After: https://1063-vertical-line-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/application/antisense-oligonucleotides
- After: https://1063-vertical-line-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/gene-therapy
=> 1063 [Bug] Vertical line displayed on Application/Solutions pages cards

blocks/card-list/card-list.js, blocks/card-list/libraryCard.js, styles/styles.css
Fix #1068 
Test URLs:
- After: https://1068-remove-dates--danaher-ls-aem--hlxsites.hlx.page/us/en/library
=> 1068 [Hubs] Library Hub Remove Dates

blocks/articles-list/articles-list.js
Fix #1072
Test URLs:
- After: https://1072-homepage-update--danaher-ls-aem--hlxsites.hlx.live/
=> 1072 Homepage UX Changes

blocks/product-hero/product-hero.js
Fix #1080
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/qpix-microbial-colony-pickers
- After: https://1080-bug-missing-rfq--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/qpix-microbial-colony-pickers
=> 1080 Missing RFQ

blocks/articles-list/articles-list.js
Fix #1078 
Test URLs:
- After: https://1078-news-articles-filtering--danaher-ls-aem--hlxsites.hlx.page/
- After: https://1078-news-articles-filtering--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/beckman-coulter-life-sciences
=> 1078 News Articles - Filtered to only pick up News and not to filter brand on homepage

blocks/page-jump-menu/page-jump-menu.js, blocks/page-tabs/page-tabs-dev.css, blocks/page-tabs/page-tabs.css, blocks/page-tabs/page-tabs.js, icons/chevron-down.svg, styles/styles.css
Fix #1067
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biozen-biologics-lc-columns
- After: https://1067-bug-jump-menu-icons--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/biozen-biologics-lc-columns
- After: https://1067-bug-jump-menu-icons--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
=> Jump-Menu/Page-Tabs icons

component-models.json
Fix #1083 
Test URLs:
- After: https://ue-cta-fix--danaher-ls-aem--hlxsites.hlx.page/
=> [UE] cta fix

blocks/timeline/timeline.css, blocks/timeline/timeline.js, build-css.js, styles/styles.css, styles/tailwind.css
Fix #1119 
Test URLs:
- After: https://1119-timeline-h2-element--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps
=> [Bug] Timeline block h2 element broken

blocks/mini-teasers/mini-teasers.css, blocks/mini-teasers/mini-teasers.js
Fix #1125
Test URLs:
- After: https://1125-mini-teaser-icons-issue--danaher-ls-aem--hlxsites.hlx.page/
=> 1125 mini-teaser-icons-issue

blocks/articles-list/articles-list.css, blocks/call-to-action/call-to-action.css, blocks/call-to-action/call-to-action.js, blocks/card-list/articleCard.js, blocks/card-list/card-list.css, blocks/cards/cards.css, blocks/cards/cards.js, blocks/carousel/carousel.js, blocks/columns/columns.js, blocks/header/header.css, blocks/header/header.js, blocks/product-category-list/product-category-list.css, blocks/product-category-list/product-category-list.js, blocks/product-overview/product-overview.css, blocks/product-overview/product-overview.js, blocks/related-articles/related-articles.css, build-css.js, styles/styles.css, styles/tailwind.css
Fix #1127 
Test URLs:
- After: https://1127-product-homepage-categories-list--danaher-ls-aem--hlxsites.hlx.page/us/en/products
- After: https://1127-product-homepage-categories-list--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/sciex
=> 1127 Product Homepage Category List

.hlxignore, .stylelintrc.json, package.json, templates/brandHome/brandHome-dev.css
Test URLs:
- After: https://update-lint-files--danaher-ls-aem--hlxsites.hlx.page/
=> [FIX] Updated lint files

.eslintrc.js, tools/actions/convert/test/fixtures/en-converted.html, tools/actions/convert/test/fixtures/en.html, tools/importer/transformers/logoCloud.js
Fix #1141 
Test URLs:
- After: https://1141-converter-logo-cloud--danaher-ls-aem--hlxsites.hlx.page/
=> 1141 [ReBrand] Converter update for logo-cloud

.eslintrc.js, blocks/workflow-carousel/workflow-carousel.js
Fix #1046 
Test URLs:
- After: https://1046-workflow-icons--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
=> 1046 [Bug] On the workflow-carousel the icons don't always show

styles/styles.css, styles/tailwind.css
Fix #1140 
Test URLs:
- After: https://1140-seo-product-page-cls-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
- After: https://1140-seo-product-page-cls-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-auc-analytical-ultracentrifuge
=> Fixed height for jump menu for Product Details

blocks/embed/embed.js, blocks/logo-clouds/logo-clouds.css, blocks/logo-clouds/logo-clouds.js, styles/styles.css, styles/tailwind.css
Fix #1133 
Test URLs:
- After: https://1133-about-us-rebrand--danaher-ls-aem--hlxsites.hlx.page/us/en/about-us
- After: https://1133-about-us-rebrand--danaher-ls-aem--hlxsites.hlx.page/us/en/about-us/danaher-business-system
=> 1133 [ReBrand] About Us and DBS Page redesign and implement in Crosswalk

blocks/product-recommendations/product-recommendations.js, scripts/commerce.js, styles/styles.css
Fix #1149
Test URLs:
- After: https://1149-prod-recom-source--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> 1149 [Product] Product Recommendations click event source is missing

blocks/embed/embed.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/about-us
- After: https://fix-height-embed--danaher-ls-aem--hlxsites.hlx.page/us/en/about-us
=> Updated embed height

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js, styles/styles.css, styles/tailwind.css
Fix #1166 
Test URLs:
- After: https://1166-product-h4--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/dm500-educational-microscope
- After: https://1166-product-h4--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/dmi1-inverted-microscopes
=> 1166 Product H4 Styling and Global Header Styling

blocks/breadcrumb/breadcrumb.css, blocks/header/header.css, blocks/header/header.js
Fix #1171 
Test URLs:
- After: https://1171-bug-navigation-not-scrolling-all--danaher-ls-aem--hlxsites.hlx.page/
=> [Bug] 1171 Navigation not scrolling all the way down

blocks/card-list/card-list.js
Fix #1175 
Test URLs:
- After: https://1175-temppage-in-index--danaher-ls-aem--hlxsites.hlx.page/us/en/library
=> 1175 [Bug] Template Page showing in index list

blocks/columns/columns.css, blocks/columns/columns.js, blocks/social-media/social-media.css, blocks/social-media/social-media.js, styles/styles.css, styles/tailwind.css
Fix #1180 
Test URLs:
- After: https://1180-ux-blognews-hero-padding--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters
- After: https://1180-ux-blognews-hero-padding--danaher-ls-aem--hlxsites.hlx.page/us/en/news/launch-of-os-software-to-brings-support-for-qtrap-system-functionality
- After: https://1180-ux-blognews-hero-padding--danaher-ls-aem--hlxsites.hlx.page/us/en/news/10x-genomics-partner-to-enable-single-cell-workflow-automation
=> 1180 UX Blog and News Hero Image Redesign

scripts/schema.js
Fix #1189 
Test URLs:
- After: https://1189-product-item-list-schema--danaher-ls-aem--hlxsites.hlx.page/us/en/products/capillary-electrophoresis-systems
=> [SEO] 1189 Created separate object for item and added the type

blocks/card-list/card-list.css, blocks/card-list/card-list.js, blocks/side-nav/side-nav.css, blocks/side-nav/side-nav.js, styles/styles.css, styles/tailwind.css
Fix #1192 
Test URLs:
- After: https://1192-ux-process-steps-rebrand--danaher-ls-aem--hlxsites.hlx.page/
=> 1192 [UX] Process Steps and Blog/News Rebrand

scripts/quote-modal.js
Fix #1198 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/intabio-zt-systems
- After: https://1198-RFQ-Image-Fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/intabio-zt-systems
=> fix: [Bug] images reference not sent in the RFQ API call

blocks/card-list/card-list.js, blocks/product-card/product-card.js, blocks/product-category/product-category.js, blocks/product-family/product-family.js, blocks/side-nav/side-nav.js, blocks/timeline/timeline.js, blocks/workflow-tabs/workflow-tabs.js, scripts/schema.js
Fix #1204 
Test URLs:
- After: https://1204-itemlist-schema-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://1204-itemlist-schema-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps
- After: https://1204-itemlist-schema-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/process-steps/sequence-verification
- After: https://1204-itemlist-schema-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
- After: …
=> [SEO] 1204 Item list schema for Workflows, Blogs and News pages

component-models.json
=> updated accordion and carousel

blocks/carousel/carousel.js
=> Fixed minor issue on carousel

blocks/accordion/accordion.js, blocks/carousel/carousel.js, component-models.json, package-lock.json, tools/actions/convert/test/fixtures/product4-converted.html
Test URLs:
- After: https://fix-ue-accordion--danaher-ls-aem--hlxsites.hlx.page/
- After: https://fix-ue-accordion--danaher-ls-aem--hlxsites.hlx.page/us/en/products
=> Fixed layout issue for carousel and accordion for UE

component-definition.json
Test URLs:
- After: https://fix-ue-home-page--danaher-ls-aem--hlxsites.hlx.page/
=> Updated the component definition

blocks/cards/cards.js
Test URLs:
- After: https://fix-cards-home-ue--danaher-ls-aem--hlxsites.hlx.page/
=> Updated cards block for UE

blocks/columns/columns.css, blocks/logo-clouds/logo-clouds.css, blocks/product-overview/product-overview.css, blocks/workflow-tabs/workflow-tabs.css, blocks/workflow-tabs/workflow-tabs.js, build-css.js, styles/styles.css, styles/tailwind.css, tailwind.config.js, templates/application/application.css
Fix #1221 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://1221-ux-solutions-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
=> 1221 UX Solutions Pages

blocks/embed/embed.css, blocks/embed/embed.js
Fix #1235 
Test URLs:
- After: https://1235-video-width-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/imagexpress-micro-confocal-high-content-imaging-systems
- After: https://1235-video-width-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers
- After: https://1235-video-width-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica
=> 1235 [Bug] Embed video not rendered width issue

component-definition.json, component-models.json
=> Updated the options name

component-models.json
=> Added the heading text field for article list

component-models.json
=> Updated options model

tools/actions/convert/src/index.js
Reverts hlxsites/danaher-ls-aem#1234
=> Revert "[UE] migrate News pages"

tools/actions/convert/test/fixtures/expert-bak-converted.html, tools/actions/convert/test/fixtures/expert-bak.html, tools/importer/transformers/embedScript.js
Fix #1244 
Test URLs:
- After: https://1244-forms-converter-updates--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/expert-bak.html
=> 1244 [Forms] Converter updates to Marketo Form (For SFDC TTAE)

tools/actions/convert/test/fixtures/expert-bak-converted.html, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions.html, tools/actions/convert/test/fixtures/talk-to-expert-converted.html, tools/actions/convert/test/fixtures/talk-to-expert.html, tools/importer/transformers/embedScript.js
Fix #1251 
Test URLs:
- After: https://1251-converter-changes-form--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/expert-bak.html
=> 1251 [Forms] Converter changes to Marketo SFDC Form

styles/styles.css, styles/tailwind.css
Fix #1254 
Test URLs:
- After: https://1254-stats-block--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy/mrna-development-manufacturing/talk-to-expert
=> 1254 [Solutions] Stats block reduce padding top

blocks/talk-to-an-expert-form/talk-to-an-expert-form.css, blocks/talk-to-an-expert-form/talk-to-an-expert-form.js, build-css.js, icons/dropdown.svg, styles/styles.css, styles/tailwind.css
Fix #1242 
Test URLs:
- After: https://1242-forms-ttae-franklin--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/expert-bak
=> 1242 [Forms] Implement the SFDC forms for Franklin

blocks/talk-to-an-expert-form/talk-to-an-expert-form.js
Fix #1256 
Test URLs:
- After: https://1256-forms-datalayer--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/expert-bak.html
=> 1257 [Bug] Added datalayer event to submit

styles/styles.css, styles/tailwind.css
Fix #1259 
Test URLs:
- After: https://1259-homepage-carousel--danaher-ls-aem--hlxsites.hlx.page/
=> 1259-homepage-carousel

blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/mini-teasers/mini-teasers.css, blocks/mini-teasers/mini-teasers.js
Fix #1259 
Test URLs:
- After: https://1259-homepage-carousel--danaher-ls-aem--hlxsites.hlx.page/
=> 1259 Fixed padding on Mini Teasers

styles/styles.css, styles/tailwind.css
Fix #1269 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/library/aav-purification
- After: https://1269-h4-header-tags--danaher-ls-aem--hlxsites.hlx.page/us/en/library/aav-purification
=>  1269 H4 Header Tag configurations

styles/styles.css, styles/tailwind.css
Fix #1271
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microplate-readers/multi-mode-readers
- After: https://1271-links-content--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microplate-readers/multi-mode-readers
=> 1271 Links on Product Taxonomy Pages

styles/styles.css, styles/tailwind.css
Fix #1276 
Test URLs:
- After: https://1276-bug-button-colours--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development
- After: https://1276-bug-button-colours--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs
- After: https://1276-bug-button-colours--danaher-ls-aem--hlxsites.hlx.page/us/en/products/microplate-readers
- After: https://1276-bug-button-colours--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mrna-therapy/mrna-development-manufacturing
=> 1276-bug-button-colours

scripts/commerce.js
Fix #1283 
Test URLs:
- After: https://1283-products-slug-url--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> 1283-products-slug-url

styles/styles.css, styles/tailwind.css
Fix #1286 
Test URLs:
- After: https://1286-cta-subtext--danaher-ls-aem--hlxsites.hlx.page/
=> 1286-cta-subtext

blocks/product-children/product-children.js, blocks/product-resources/product-resources.js, scripts/commerce.js, scripts/delayed.js
Fix #1288 
Test URLs:
- After: https://api-token-fix--danaher-ls-aem--hlxsites.hlx.page/
- After: https://api-token-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
=> Fix for the API token naming to follow AEM pages (Quotes/checkout)

blocks/header/header.js
Fix #<1294>
Test URLs:
- After: https://js-issue-fix--danaher-ls-aem--hlxsites.hlx.page/
=> fix for console error when quote cart is empty[#1294]

tools/actions/convert/test/fixtures/addtionalstyle-test-converted.html, tools/actions/convert/test/fixtures/addtionalstyle-test.html, tools/importer/transformers/fullLayoutSection.js
=> [wsaw]-fix for 2 column width layout

tools/importer/transformers/miniTeaser.js
=> Updated miniteaser

tools/importer/transformers/embedScript.js
=> Updated script converter

tools/importer/transformers/index.js, tools/importer/transformers/product-not-found.js
=> Added empty block for product not found

blocks/spline-viewer/spline-viewer.js, fragments/spline.html, tools/importer/transformers/index.js, tools/importer/transformers/spline-viewer.js
Fix #1316 
Test URLs:
- After: https://1316-spline-fragment--danaher-ls-aem--hlxsites.hlx.page/
=> Created for spline-fragment

blocks/columns/columns.css, blocks/columns/columns.js, blocks/mini-teasers/mini-teasers.js, blocks/product-hero/product-hero.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://wsaw-fdbk-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/we-see-a-way
=> wsaw feedback fix for Home and details page

blocks/spline-viewer/spline-viewer.css, blocks/spline-viewer/spline-viewer.js, build-css.js, fragments/spline.html, head.html, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://fix-spline-viewer--danaher-ls-aem--hlxsites.hlx.page/
=> Fixed spline viewer issue

tools/importer/transformers/metadata.js
=> Added solution metadata

blocks/product-hero/product-hero.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/ab150686-abcam
- After: https://prod-price--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/ab150686-abcam
=> removed console stmt and test message from product hero

blocks/card-list/card-list.js
Test URLs:
- After: https://fix-weseeaway-hub--danaher-ls-aem--hlxsites.hlx.page/
=> Updated the content type

blocks/card-list/card-list.js, helix-query.yaml
Test URLs:
- After: https://minor-fix-wsaw--danaher-ls-aem--hlxsites.hlx.page/
=> Minor update for wsaw

blocks/card-list/card-list.js
Test URLs:
- After: https://minor-fix-wsaw--danaher-ls-aem--hlxsites.hlx.page/
=> Updated wsaw

tools/importer/transformers/cardList.js
=> Added styles

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://colimgresize-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development 
-
=> column img resize issue fixed and reflecting only for wsaw page

blocks/card-list/card-list.js
Test URLs:
- Before: https://stage.lifesciences.danaher.com/us/en/we-see-a-way/solutions/analytical-tools.html 
- After: https://fix-wsaw-index-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/we-see-a-way/solutions/analytical-tools 
-
=> fix on cardlist js file for the console error

scripts/schema.js
Fix #1349
Test URLs:
- Before: https://lifesciences.danaher.com/us/en/solutions/mabs/cell-line-development/products.html
- After: https://fix-itemlistschema--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> fix for ItemList Schema- updated to description instead of excerpt

blocks/card-list/card-list.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog 
- After: https://fix-null-cardlist--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
=> fix for null in cardlist

scripts/schema.js
Test URLs:
- Before: https://stage.lifesciences.danaher.com/us/en/solutions/mabs/cell-line-development/products.html 
- After: https://fix-schema-itemlist--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products
=> fix for itemschema element description

blocks/header/header.js, blocks/talk-to-an-expert-form/talk-to-an-expert-form.js
Fix #1342
Test URLs:
- After: https://fix-accessibility--danaher-ls-aem--hlxsites.hlx.page/
=> Fix accessibility

converter.yaml, tools/actions/convert/src/index.js
=> Updated for publish metadata-product JSON

tools/actions/convert/src/index.js
=> Fix publish url

styles/styles.css, styles/tailwind.css
Fix #1280
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/ab65620-abcam
- After: https://1280-pdp-short-description--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/ab65620-abcam
=> 1280-pdp-short-description

tools/actions/convert/src/index.js
=> Added location header

.eslintignore
=> Added index to git ignore

blocks/columns/columns.js, blocks/page-jump-menu/page-jump-menu.js
Fix #1374 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab
- After: https://1374-jumpmenu-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab
=> Jumpmenu issue on new-lab page creation

blocks/product-hero/product-hero.js
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/ab10278-abcam#specifications 
- After:  https://fix-nan--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/ab10278-abcam#specifications
-
=> Fix for NaN issue for family

fragments/footer.html, head.html
Updated date
Fix #1372 
Test URLs:
- After: https://1372-org-schema--danaher-ls-aem--hlxsites.hlx.page/
=> 1372-org-schema

blocks/product-hero/product-hero.js
Test URLs:
- After: https://fix-almetadatavalues--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/ab172730-abcam
-
=> fix- changed from allmetadatavalues to listpriceusd

blocks/articles-list/articles-list.js
Fix #<1362>
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/leica
- After: https://1362-index-news-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/leica
=> News pages not showing on LSIG #1362

blocks/card-list/articleCard.js, blocks/card-list/card-list.js, helix-query.yaml
Fix #1364 
Test URLs:
- After: https://1364-new-lab-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab
=> 1364 new lab pages changes

blocks/card-list/articleCard.js, blocks/card-list/card-list.js, blocks/new-lab/newlab-join-today-form.css, blocks/new-lab/newlab-join-today-form.js, build-css.js, styles/styles.css, styles/tailwind.css
=> added block for new-lab

fstab.yaml
=> Updated URL back stage

converter.yaml
=> Updated stage host back

blocks/opco-consent/opco-consent.js
Test URLs:
- After: https://popup-fix--danaher-ls-aem--hlxsites.hlx.page/
=> fix for boomi api call trigger

fragments/tiled.html
Fix #1363 
Test URLs:
- After: https://1363-new-tiled-block--danaher-ls-aem--hlxsites.hlx.page/
=> reduced width

blocks/join-today-form/join-today-form.js, blocks/opco-consent/opco-consent.js
=> 1364 new lab pages

helix-query.yaml
=> helix-quer update

tools/actions/convert/test/fixtures/megamenu_items_us.json
=> update videos menu

tools/actions/convert/test/fixtures/new-home-page.html
=> megamenu update

tools/actions/convert/test/fixtures/header-converted.html
=> header menu update

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-ktchid--danaher-ls-aem--hlxsites.hlx.page/
=> fix for dynamic getItem

head.html
Fix #1398
Test URLs:
- After: https://1398-schema-org--danaher-ls-aem--hlxsites.hlx.page/
=> 1398-schema-org

blocks/opco-consent/opco-consent.js, tools/importer/transformers/accordion.js
Fix #1379 
Test URLs:
- After: https://1425-new-lab-overiew--danaher-ls-aem--hlxsites.hlx.page/
=> opco changes

tools/actions/convert/test/fixtures/header-converted.html, tools/actions/convert/test/fixtures/newlab-join-today-converted.html, tools/importer/transformers/accordion.js
Test URLs:
- After: https://new-lab-home-page-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab
=> Updated converter for new-lab home page

tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category-tags-converted.html, tools/actions/convert/test/fixtures/product-category1-converted.html, tools/actions/convert/test/fixtures/product-category2-converted.html, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions1-converted.html, tools/importer/transformers/accordion.js, tools/importer/transformers/workflowContainer.js
=> Fixed two col section issue

fragments/tiled.html
Fix #1425 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab/tiled.html/
- After: https://fix-tile--danaher-ls-aem--hlxsites.hlx.page/us/en/new-lab/tiled.html/
=> footer overlap fixed

tools/actions/convert/test/fixtures/product-category-converted.html, tools/actions/convert/test/fixtures/product-category-tags-converted.html, tools/actions/convert/test/fixtures/product-category1-converted.html, tools/actions/convert/test/fixtures/product-category2-converted.html, tools/actions/convert/test/fixtures/solutions-converted.html, tools/actions/convert/test/fixtures/solutions1-converted.html, tools/importer/transformers/workflowContainer.js
=> Fixed two col

helix-query.yaml, paths.yaml, tools/importer/transformers/util.js
=> Updated the index

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-ketch-stringfy--danaher-ls-aem--hlxsites.hlx.page/
=> fix for request body format with json stringify

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-emailurl--danaher-ls-aem--hlxsites.hlx.page/
=> opco url email presence

blocks/columns/columns.css, blocks/columns/columns.js
=> Updated for join today form

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://new-boomiapi--danaher-ls-aem--hlxsites.hlx.page/
=> changed boomi api call

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-emailvalue--danaher-ls-aem--hlxsites.hlx.page/
=> fix email value throwing null on ok button event in the modal

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-domainspecific--danaher-ls-aem--hlxsites.hlx.page/
=> storage email value encoded

paths.json, paths.yaml, tools/importer/transformers/productHero.js
Fix #1448 
Test URLs:
- After: https://1448-insert-product-records--danaher-ls-aem--hlxsites.hlx.page/
=> update products metadata json

paths.json, paths.yaml
Fix #1448 
Test URLs:
- After: https://1448-insert-product-records--danaher-ls-aem--hlxsites.hlx.page/
=> revert the path

blocks/card-list/card-list.js
Fix #1451 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/library
- After: https://1451-bugfix-library-page-index--danaher-ls-aem--hlxsites.hlx.page/us/en/library
=> 1451-bugfix-library-page-index

tools/actions/convert/test/fixtures/header-converted.html, tools/actions/convert/test/fixtures/megamenu_items_us.json, tools/actions/convert/test/fixtures/new-home-page.html
Fix #1459
Test URLs:
- After: https://1459-new-lab-mega-menu--danaher-ls-aem--hlxsites.hlx.page/
=> fix for newlab megamenus

scripts/commerce.js
Fix #1457 
Test URLs:
- After: https://fix-boomi-opco--danaher-ls-aem--hlxsites.hlx.page/
=> fix for Products Metadata backup using Product Data API

scripts/commerce.js
Fix #1457 
Test URLs:
- After: https://fix-productdata--danaher-ls-aem--hlxsites.hlx.page/
=> fix for meta description

blocks/opco-consent/opco-consent.js, scripts/commerce.js
Fix #1379 
Test URLs:
- After: https://fix-boomi-tkn--danaher-ls-aem--hlxsites.hlx.page/
=> fix for opco user_email and meta description

blocks/opco-consent/opco-consent.js, scripts/commerce.js
=> branch update

blocks/opco-consent/opco-consent.js, scripts/commerce.js
Fix #1379 
Test URLs:
- After: https://hide-token--danaher-ls-aem--hlxsites.hlx.page/
=> fix for opco token and canonical in commerce js

scripts/commerce.js
Fix #1457 
Test URLs:
- After: https://fix-canonical--danaher-ls-aem--hlxsites.hlx.page/
=> fix for link canonical with html extn

blocks/columns/columns.js
=> 1455 gated videos

blocks/columns/columns.js
=> 1455 gated video

blocks/opco-consent/opco-consent.css, blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://chg-hide-tkn--danaher-ls-aem--hlxsites.hlx.page/
=> included token for prod and stage env

scripts/commerce.js
Fix #1457 
Test URLs:
- After: https://fix-meta-brand--danaher-ls-aem--hlxsites.hlx.page/
=> added meta for brand

blocks/columns/columns.js
Fix #1475 
Test URLs:
- After: https://1475-gated-video-utm-campaign--danaher-ls-aem--hlxsites.hlx.page/
=> 1475-gated-video-utm-campaign

blocks/opco-consent/opco-consent.js
=> opco update

blocks/opco-consent/opco-consent.js
=> env update

tools/actions/convert/src/index.js
=> Updated for JSON publish

blocks/opco-consent/opco-consent.js
=> email update

converter.yaml
=> Updated the product metadata path

tools/importer/transformers/metadata.js
=> pageorderupdate

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-clickarea--danaher-ls-aem--hlxsites.hlx.page/
=> loader added

tools/importer/transformers/metadata.js
=> pageordr update

tools/importer/transformers/metadata.js
=> pageorder update1

blocks/opco-consent/opco-consent.js
Fix #1379 
Test URLs:
- After: https://fix-separate-boomicall--danaher-ls-aem--hlxsites.hlx.page/
=> separated boomi call and removed loader

blocks/side-nav/side-nav.js
Fix #1383 
Test URLs:
- After: https://fix-sidenavorder--danaher-ls-aem--hlxsites.hlx.page/
=> sorted pageorder for sidenav

blocks/opco-consent/opco-consent.js, blocks/side-nav/side-nav.css, blocks/side-nav/side-nav.js
Fix 1455-gated-videos
Test URLs:
=> 1455-gated-videos

blocks/columns/columns.js
=> added country field

blocks/tiled-viewer/tiled-viewer.css, blocks/tiled-viewer/tiled-viewer.js, styles/styles.css, styles/tailwind.css
Fix #1436 
Test URLs:
- After: https://fix-tilemargin--danaher-ls-aem--hlxsites.hlx.page/
=> fix for tile margins in high resolution viewport

fragments/tiled.html
Fix #1436 
Test URLs:
- After: https://fix-greybkground--danaher-ls-aem--hlxsites.hlx.page/
=> fix for grey background removal

scripts/quote-modal.js
Fix #1516 
Test URLs:
- After: https://fix-multiopco--danaher-ls-aem--hlxsites.hlx.page/
=> fix for checkig multibrand opcos

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js
Fix #1518 
Test URLs:
- After: https://fix-pdpfamily-rfq--danaher-ls-aem--hlxsites.hlx.page/
=> showing rfq button even if price there

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js
Fix #1518 
Test URLs:
- After: https://fix-rfqbtnborder--danaher-ls-aem--hlxsites.hlx.page/
=> removed button border right and left

blocks/product-hero/product-hero.js
Fix #1518 
Test URLs:
- After: https://fix-rfqmodal--danaher-ls-aem--hlxsites.hlx.page/
=> fix modal for sku products

blocks/product-hero/product-hero.js
Fix #1518
Test URLs:
- After: https://fix-rfqalignment--danaher-ls-aem--hlxsites.hlx.page/
=> fix for rfq alignments

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js
Fix #1518
Test URLs:
- After: https://fix-rfq-allrow--danaher-ls-aem--hlxsites.hlx.page/
=> buttons aligned as single row

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js
Fix #1518 
Test URLs:
- After: https://fix-responsive-pdp--danaher-ls-aem--hlxsites.hlx.page/
=> responsive fix for brand and rfq btns

blocks/columns/columns.js
Fix #1532 >
Test URLs:
- After: https://1532-hrm-form-coloumnjs-update--danaher-ls-aem--hlxsites.hlx.page/
=> Opco update.

blocks/tiled-viewer/tiled-viewer.css, blocks/tiled-viewer/tiled-viewer.js, fragments/tiled.html, tools/importer/transformers/embedScript.js
Fix #1540 
Test URLs:
- After: https://fix-tile--danaher-ls-aem--hlxsites.hlx.page/
=> Fix tile calling throug embed instead of fragments

blocks/columns/columns.js
Test URLs:
- After: https://feature-newlab-jointoday--danaher-ls-aem--hlxsites.hlx.page/
=> form changes for new lab join today page

tools/actions/convert/src/index.js
Fix #update-skip-converter
Test URLs:
https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
After: https://update-skip-converter--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
=> Updated the regex to consider the pages under products

styles/styles.css, styles/tailwind.css
Fixing breadcrumb and shop / opco pages
Test URLs:
- After: https://em1-shop-fixes--danaher-ls-aem--hlxsites.hlx.page/
=> fixing breadcrumb

blocks/top-selling-products/_top-selling-products.json, blocks/top-selling-products/gridData.js, blocks/top-selling-products/top-selling-products.css, blocks/top-selling-products/top-selling-products.js
Adding top selling products block 
Test URLs:
- After: https://em1-shop-fixes--danaher-ls-aem--hlxsites.hlx.page/
=> adding top selling

blocks/accordion-container/accordion-container.css, blocks/accordion-container/accordion-container.js
Test URLs:
Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
After: https://category-faqs-bugfix--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
=> Category faqs bugfix

templates/processstep/processstep.js
Test URLs:
- After: https://1547-solution-pages-sidebar--danaher-ls-aem--hlxsites.hlx.page/
=> 1547-solution-pages-sidebar

blocks/product-hero-content/product-hero-content.css, blocks/product-hero-content/product-hero-content.js
Test URLs:
Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
After: https://category-bugfix-v3--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/products/assay-kits/elisa-kits
=> Category bugfix v3

blocks/dual-carousel/dual-carousel.css, blocks/dual-carousel/dual-carousel.js, blocks/top-purchased-products/gridData.js, blocks/top-purchased-products/top-purchased-products.js, blocks/top-selling-products/gridData.js, blocks/top-selling-products/top-selling-products.css, blocks/top-selling-products/top-selling-products.js
Test URLs:
Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/shop-home
After: https://shop-fixes-v2--danaher-ls-aem--hlxsites.hlx.page/us/en/eds-stage-test/shop-home
=> Shop fixes v2

blocks/body-banner/body-banner.js, blocks/dual-carousel/dual-carousel.js, blocks/insight/insight.js, blocks/learn-more/learn-more.js, blocks/offer-banner/offer-banner.js, blocks/opco-banner/opco-banner.js, blocks/opco-grid/_opco-grid.json, blocks/opco-grid/opco-grid.css, blocks/opco-grid/opco-grid.js, blocks/page-tabs/top-selling-product.js, blocks/product-categories/product-categories.css, blocks/product-categories/product-categories.js, blocks/separator-line/separator-line.js, blocks/shop-featured-products/_shop-featured-products.json, blocks/shop-featured-products/shop-featured-products.js, blocks/simple-text/simple-text.js, blocks/top-purchased-products/top-purchased-products.js, blocks/top-selling-products/top-selling-products.js, component-models.json
Shop Fixes
Test URLs:
- After: https://eds-v2--danaher-ls-aem--hlxsites.hlx.page/
=> opco banner

blocks/carousel/carousel.js, package-lock.json, package.json, templates/processstep/processstep.js, tools/actions/convert/src/index.js
Merged with main
Test URLs:
- After: https://api-endpoints-field--danaher-ls-aem--hlxsites.hlx.page/
=> Api endpoints field

tools/actions/convert/src/index.js
Test URLs:
After: https://skip-converter-01-v2--danaher-ls-aem--hlxsites.hlx.page/
=> eMarketPlace-converter to skip the product paths

blocks/offer-advertisement/offer-advertisement.js, blocks/product-banner/product-banner.js, blocks/product-family/gridData.js, blocks/product-family/listData.js, blocks/related-category/related-category.js, blocks/top-selling/gridData.js, blocks/top-selling/listData.js, blocks/top-selling/top-selling.css
Test URL should be like below
Test URLs:
After: https://category-fix-phase-1---danaher-ls-aem--hlxsites.hlx.page/
=> removing unnecessary blocks

blocks/opco-banner/opco-banner.css, blocks/opco-banner/opco-banner.js
Shop Home Brands 
Test URLs:
- After: https://shop-home-brands--danaher-ls-aem--hlxsites.hlx.page/
=> Shop home brands

blocks/breadcrumb/_breadcrumb.json, blocks/recent-articles/_recent-articles.json, blocks/related-articles/_related-articles.json, component-definition.json, package-lock.json
Test URLs:
- After: https://feature-newsblog-new--danaher-ls-aem--hlxsites.hlx.page/
=> Feature newsblog new

blocks/opco-consent/opco-consent.js
Fix #1605 
Test URLs:
- After: https://fix-emaillowercase--danaher-ls-aem--hlxsites.hlx.page/
=> fix to ensure email in lowercase

blocks/accordion-container/accordion-container.js
Test URLs:
After: https://accordion-bugfix-v8--danaher-ls-aem--hlxsites.hlx.page/
=> Added a check in the accordion

blocks/accordion-container/accordion-container.css, blocks/accordion-container/accordion-container.js, blocks/product-family/gridData.js, blocks/product-family/product-family.css, blocks/product-family/product-family.js, blocks/product-info-list/product-info-list.css, blocks/product-info-list/product-info-list.js, blocks/top-selling/top-selling.css, blocks/top-selling/top-selling.js
PR 
Test URL should be like below
Test URLs:
After: https://top-selling-data---danaher-ls-aem--hlxsites.hlx.page/
=> Top selling data

blocks/article-info/_article-info.json, component-definition.json, component-filters.json, models/_section.json
Test URLs:
- After: https://feature-addsection--danaher-ls-aem--hlxsites.hlx.page/
=> added article info to the model section

blocks/product-family/product-family.css, blocks/product-family/product-family.js
Test URLs:
After: https://product-family-expand-collapse---danaher-ls-aem--hlxsites.hlx.page/
=> expand and collapse

scripts/commerce.js, scripts/delayed.js
Test URLs:
After: https://em1-reverting-authorization-function--danaher-ls-aem--hlxsites.hlx.page/
=> Reverted the Authorization

tools/actions/convert/src/index.js
Test URLs:
- After: https://feature-newsblog-eds--danaher-ls-aem--hlxsites.hlx.page/
=> added the news and blog eds url

tools/actions/convert/src/index.js, tools/actions/convert/src/pathConfig.json
Test URLs:
After: https://em1-converter-v5--danaher-ls-aem--hlxsites.hlx.page/
=> Reverted the converter to original state as before EDS for products path

blocks/product-hero/product-hero.js
Fix #1624 
Test URLs:
- After: https://fix-buynw-live--danaher-ls-aem--hlxsites.hlx.page/
=> changed logic of buynow btn having listprice and buynow separately

styles/styles.css, tailwind.config.js
Fonts weight not loading as expected for headings
Test URLs:
- After: https://em1-heading-font-fix--danaher-ls-aem--hlxsites.hlx.page/
=> font fixed

tools/actions/convert/src/index.js
Converter updated to work for products-eds and e-buy
Test URLs:
- After: https://em1-t395-converter-products-checkout--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 t395 converter products checkout

blocks/breadcrumb/breadcrumb.js
Test URLs:
- After: https://feature-revertbreadcrumb--danaher-ls-aem--hlxsites.hlx.page/
=> added for duplicate breadcrumb restriction

fstab.yaml
Test URLs:
After: https://em2-pdp-template-v1--danaher-ls-aem--hlxsites.hlx.page/
=> Added  redirection condition for dynamic products

blocks/opco-banner/opco-banner.js
opco banner opcos links update from product to products-eds
Test URLs:
- After: https://em1-so-fixes-18-v1--danaher-ls-aem--hlxsites.hlx.page/
=> opco banner opcos links update from product to products-eds

blocks/opco-banner/opco-banner.js, tools/actions/convert/src/index.js
Test URLs:
- After: https://em1-opcobanner-opco-link--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 opcobanner opco link

blocks/footer/footer.js, blocks/product-categories/product-categories.js
Fallback image for product categories block
Test URLs:
- After: https://em1-so-categories-fallback-images--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 so categories fallback images

blocks/product-categories/product-categories.js
Fixed Product Categories Block to remove/hide blank items.
Test URLs:
- After: https://em1-t399-product-categories-fix-21--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 t399 product categories fix 21

blocks/product-family/product-family.css, blocks/product-family/product-family.js, scripts/commerce.js
Test URLs:
After: https://pagination-fix---danaher-ls-aem--hlxsites.hlx.page/
=> pagination changes

blocks/top-purchased-products/gridData.js, blocks/top-purchased-products/top-purchased-products.css, fstab.yaml, tools/actions/convert/src/index.js
Updated fstab.yaml and added two categories in converter : 
antibodies and assay-kits
Test URLs:
- After: https://em1-converter-categories-22--danaher-ls-aem--hlxsites.hlx.page/
=> updating fstab and added 2 cats in converter

fstab.yaml
Test URLs:
After: https://em2-dynamic-page--danaher-ls-aem--hlxsites.hlx.page/
=> added changes to fstab for redirection

blocks/learn-more/learn-more.css, blocks/learn-more/learn-more.js, blocks/product-categories/product-categories.js
Aligned Learn more text on left on mobile
Reduced spacing below the categories title and categories listing
Test URLs:
- After: https://em1-t142-learnmore-mobile--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 t142 learnmore mobile

blocks/product-hero/product-hero.css, blocks/product-hero/product-hero.js
Fix #
Test URLs:
- After: https://fix-hide-listpriceinfo--danaher-ls-aem--hlxsites.hlx.page/
=> Fix hide listpriceinfo

blocks/top-selling/gridData.js, blocks/top-selling/listData.js, blocks/top-selling/top-selling.css, blocks/top-selling/top-selling.js
Fixing top-selling block.
Test URLs:
- After: https://EM-T414-Top-Selling-Hover-Transition--danaher-ls-aem--hlxsites.hlx.page/
=> Em t414 top selling hover transition

blocks/article-info-new/_article-info-new.json, blocks/article-info-new/article-info-new.js, blocks/columns/columns.js, component-models.json
Test URLs:
- After: https://feature-article-info--danaher-ls-aem--hlxsites.hlx.page/
=> updated the article info logic

tools/actions/convert/src/index.js
Test URLs:
After: https://em1-converter-stage-check-v1--danaher-ls-aem--hlxsites.hlx.page/
=> Added the Stage envi check to skip the converter

blocks/breadcrumb/breadcrumb.js, blocks/header/header.js, tools/actions/convert/src/index.js
Test URLs:
After: https://em1-stage-converter-check-v3--danaher-ls-aem--hlxsites.hlx.page/
=> Added few more checks for antibodies and assay-kits and breadcrumb

blocks/pdp-hero/pdp-hero.css, blocks/pdp-hero/pdp-hero.js
Test URLs:
After: https://feature-pdp-hero-fix---danaher-ls-aem--hlxsites.hlx.page/
=> Feature pdp hero fix

blocks/separator-line/separator-line.js
Test URLs:
- After: https://em1-fixing-separator-30--danaher-ls-aem--hlxsites.hlx.page/
=> fixing separator

blocks/columns/columns.css, blocks/columns/columns.js, styles/styles.css, styles/tailwind.css
Test URLs:
- After: https://feature-revertcolumn--danaher-ls-aem--hlxsites.hlx.page/
=> added the css class for blog and news

blocks/product-card/product-card.js, blocks/product-recommendations/product-recommendations.js, scripts/opco-mapping.js, scripts/scripts-dev.js, scripts/slug-utils.js
Test URLs:
- After: https://fix-urlslug--danaher-ls-aem--hlxsites.hlx.page/
=> fix for urlslug to use opco key instead of opco value

blocks/side-nav/side-nav.js
Fixed Sidenav with content for solutions page
Test URLs:
- After: https://em1-433-solutions-page--danaher-ls-aem--hlxsites.hlx.page/
=> fixing solutions page with sidenav

blocks/articles-list/articles-list.js, blocks/top-purchased-products/gridData.js
Fixing article / news block. Hiding the articles/news from the block if there is no brand.
Test URLs:
- After: https://em1-t432-article-news-block--danaher-ls-aem--hlxsites.hlx.page/
=> fixing article new block

blocks/dual-carousel/dual-carousel.js
Test URLs:
- After: https://em1-dual-carousel-01--danaher-ls-aem--hlxsites.hlx.page/
=> updating dual carousel

blocks/opco-banner/opco-banner.css, blocks/opco-banner/opco-banner.js
Test URLs:
- After: https://em1-04-opco-logos-v1--danaher-ls-aem--hlxsites.hlx.page/
=> updating brandlogos on opco banner block on opco pages

tools/actions/convert/src/index.js
adding 2d-3d-cell-culture-systems in converter config
Test URLs:
- After: https://em1-2d3d-converter-05--danaher-ls-aem--hlxsites.hlx.page/
=> adding 2d-3d-cell-culture-systems in converter config

tools/actions/convert/src/index.js
updating converter for prod to target only brands
Test URLs:
- After: https://em1-prod-converter-brands--danaher-ls-aem--hlxsites.hlx.page/
=> updating converter for prod to target only brands

blocks/opco-banner/opco-banner.js, blocks/product-categories/product-categories.js, scripts/delayed.js
Test URLs:
- After: https://feature-utm--danaher-ls-aem--hlxsites.hlx.page/
=> utm external link added

blocks/opco-banner/opco-banner.js, blocks/product-categories/product-categories.js
Test URLs:
- After: https://em1-i33-prod-pdf-image--danaher-ls-aem--hlxsites.hlx.page/
=> updating product image fix for pdf response

blocks/top-selling/listData.js
Test URLs:
- After: https://em1-top-selling-links--danaher-ls-aem--hlxsites.hlx.page/
=> Em1 top selling links

blocks/carousel/_carousel.json, blocks/columns/_columns.json, blocks/columns/columns.js, blocks/mini-teasers/_mini-teasers.json, component-definition.json, component-filters.json, component-models.json
Test URLs:
- After: https://feature-columns--danaher-ls-aem--hlxsites.hlx.page/
=> added the logic for columns

blocks/form/_form.json, blocks/form/form.css, blocks/form/form.js, blocks/stats/_stats.json, component-definition.json, component-filters.json, component-models.json
Test URLs:
- After: https://feature-forms--danaher-ls-aem--hlxsites.hlx.page/
=> added the forms JSON fields

tools/actions/convert/src/converter-paths-config.js, tools/actions/convert/src/index.js
Test URLs:
- After: https://em1-converter-to-exclude-pdp--danaher-ls-aem--hlxsites.hlx.page/
=> Editing converter to exclude the pdp and topics-jck

blocks/opco-banner/_opco-banner.json, blocks/product-banner/_product-banner.json, component-models.json
Test URLs:
- After: https://em1-revert-title-tags-fix-22--danaher-ls-aem--hlxsites.hlx.page/
=> reverting the title tag type from json

tools/actions/convert/src/index.js
Test URLs:
- After: https://em1-converter-fix-v221--danaher-ls-aem--hlxsites.hlx.page/
=> updating converter logic to exclude pages

helix-query.yaml
Test URLs:
- After: https://em1-helix-query-fix-221--danaher-ls-aem--hlxsites.hlx.page/
=> updating category title case

blocks/banner/banner.css, blocks/banner/banner.js, blocks/card-list/card-list.js, blocks/columns/columns.css, blocks/columns/columns.js
Test URLs:
- After: https://feature-25082025--danaher-ls-aem--hlxsites.hlx.page/
=> Feature 25082025

blocks/carousel/_carousel.json, component-filters.json, component-models.json
Test URLs:
- After: https://feature-carousel-change--danaher-ls-aem--hlxsites.hlx.page/
=> added carousel JSON changes

component-filters.json, models/_section.json
Test URLs:
- After: https://feature-mini-teasers--danaher-ls-aem--hlxsites.hlx.page/
=> added the mini teasers json

blocks/columns/columns.js, blocks/form/form.js
Test URLs:
- After: https://feature-form-changes--danaher-ls-aem--hlxsites.hlx.page/
=> Feature form changes

blocks/columns/columns.js
Test URLs:
- After: https://feature-form-changes--danaher-ls-aem--hlxsites.hlx.page/
=> added the form logic

tools/actions/convert/src/converter-paths-config.js
Test URLs:
- After: https://feature-resources--danaher-ls-aem--hlxsites.hlx.page/
=> added resources to exclude path

tools/actions/convert/src/converter-paths-config.js
Test URLs:
- After: https://em1-converter-change-29-v2--danaher-ls-aem--hlxsites.hlx.page/
=> adding we-see-a-way in converter include array

tools/actions/convert/src/converter-paths-config.js, tools/actions/convert/src/index.js
Test URLs:
- After: https://em1-converter-fix-29-v3--danaher-ls-aem--hlxsites.hlx.page/
=> updating converter to work fro prod

blocks/banner/banner.css, blocks/banner/banner.js, blocks/card-list/card-list.js, blocks/columns/columns.css, blocks/columns/columns.js, blocks/opco-consent/opco-consent.js
Test URLs:
- After: https://feature-backup-29082025--danaher-ls-aem--hlxsites.hlx.page/
=> reverting the next release changes

blocks/product-banner/product-banner.js, blocks/product-children/product-tile.js, blocks/product-family/gridData.js, blocks/product-family/listData.js, blocks/top-selling/gridData.js, blocks/top-selling/listData.js
Test URLs:
- After: https://EM1-T454-production-card-bug--danaher-ls-aem--hlxsites.hlx.page/
=> card redirect to same page

blocks/columns/columns.js, blocks/form/_form.json, component-models.json
Test URLs:
- After: https://feature-forms-columns--danaher-ls-aem--hlxsites.hlx.page/
=> added the form logic JSON

blocks/tags-list/_tags-list.json, blocks/tags-list/tags-list.js, component-models.json
Test URLs:
- After: https://feature-tags-list--danaher-ls-aem--hlxsites.hlx.page/
=> added the tags-list JSON

blocks/pdp-hero/pdp-hero.js
- After: https://pdp-bug-fix--danaher-ls-aem--hlxsites.hlx.page/
=> fixed pdp bugs

templates/blog/blog.js
Test URLs:
- After: https://feature-topics--danaher-ls-aem--hlxsites.hlx.page/
=> added the topics JSON

templates/blog/blog.js
Test URLs:
- After: https://feature-main17092025--danaher-ls-aem--hlxsites.hlx.page/
=> reverted the pdp files to push to prod
