tools/actions/convert/test/fixtures/header-semantic.html
tools/importer/import.js

The colon (`:`) char is used by html pipeline to create <span> elements. Hence it's not appropriate to be used as separator for menu title. Changed to `|` char for separator.
Test URLs:
- After: https://feat-6-separator--danaher-ls-aem--hlxsites.hlx.page/

fix: change separator in megamenu title

---

blocks/logo-clouds/logo-clouds.js

Fix #123
Test URLs:
- After: https://fix-123-lc-links--danaher-ls-aem--hlxsites.hlx.live/

fix: open cloud logo links in now tab

---

blocks/cards/cards.js
tools/actions/convert/test/fixtures/application-detail1-converted.html
tools/importer/transformers/cards.js
tools/importer/transformers/fullLayoutSection.js

Fix #512 
Test URLs:
- After: https://512-converter-update-for-application--danaher-ls-aem--hlxsites.hlx.page/us/en/application/antisense-oligonucleotides

512 Updated converter to get card on application page

---

scripts/scripts.js

Test URLs:
- After: https://bug-disable-autoBlockHero--danaher-ls-aem--hlxsites.hlx.page/
- After: https://bug-disable-autoBlockHero--danaher-ls-aem--hlxsites.hlx.page/us/en/blog
- After: https://bug-disable-autoBlockHero--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/antisense-oligonucleotides-manufacturing-advances
- After: https://bug-disable-autoBlockHero--danaher-ls-aem--hlxsites.hlx.page/us/en/news
- After: https://bug-disable-autoBlockHero--danaher-ls-aem--hlxsites.hlx.page/us/en/news/new-system-fully-integrates-icief-uv-and-mass-spectrometry
- …

Removed buildHeroBlock from script JS

---

tools/actions/convert/test/fixtures/blog.html
tools/actions/convert/test/fixtures/blog6.html
tools/actions/convert/test/fixtures/product-topic.html
tools/actions/convert/test/fixtures/product1.html
tools/importer/transformers/util.js

Fix #534 
Test URLs:
- After: https://534-topics-page-h3-seen-as-h2--danaher-ls-aem--hlxsites.hlx.page/

Featured Image component in Topics - h3 seen as h2

---

blocks/columns/columns.css
blocks/columns/columns.js
styles/styles.css
tools/actions/convert/test/fixtures/blog2-converted.html
tools/actions/convert/test/fixtures/product1-converted.html
tools/importer/transformers/twoColumns.js

Fix #541 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- After: https://541-converter-update-for-column--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency

541-converter-update-for-column

---

blocks/card-list/card-list.js
tools/importer/transformers/cardList.js

Test URLs:
- After: https://516-info-hub-template-change--danaher-ls-aem--hlxsites.hlx.page/

Info Hub can be the same as Application Hub template

---

blocks/cards/cards.css
blocks/cards/cards.js
styles/styles.css
tools/actions/convert/test/fixtures/product1-converted.html
tools/actions/convert/test/fixtures/product1.html
tools/importer/transformers/cards.js
tools/importer/transformers/columns.js

Fix #508 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
- After: https://508--danaher-ls-aem--hlxsites.hlx.page/us/en/product1

feat: implement product opco cards

---

tools/actions/convert/test/fixtures/en-converted.html
tools/actions/convert/test/fixtures/product-opco-home-converted.html
tools/actions/convert/test/fixtures/product1-converted.html
tools/actions/convert/test/fixtures/product1.html
tools/importer/transformers/callToAction.js
tools/importer/transformers/cards.js
tools/importer/transformers/carousel.js
tools/importer/transformers/fullLayoutSection.js

Test URLs:
- After: https://569-new-section-carousel-first-full-layout--danaher-ls-aem--hlxsites.hlx.page/

569-new-section-carousel-first-full-layout

---

blocks/cards/cards.css
styles/styles.css

Test URLs:
- After: https://572-image-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/products

fix: adjust object fit for opco card images

---

blocks/carousel/carousel.js

Fix #615 
Test URLs:
- After: https://615--danaher-ls-aem--hlxsites.hlx.page/us/en/products

fix: carousel not working on Firefox

---

blocks/product-resources/product-resources.js
scripts/scripts.js
templates/productDetail/productDetail.js

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers
- After: https://620-minor-fix-for-sku--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers

Minor fix for sku reading from URL

---

blocks/product-hero/product-hero.css
blocks/product-hero/product-hero.js
blocks/product-parts/product-parts.js
styles/styles.css

Fix #679 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/m80-ergonomic-stereo-microscopes-for-inspection-with-removable-integrated-camera#product-details
- After: https://679-ui-bundle-product-detail-tab--danaher-ls-aem--hlxsites.hlx.page/us/en/products/bundles/m80-ergonomic-stereo-microscopes-for-inspection-with-removable-integrated-camera#product-details

679 UI for bundle product parts tab

---

tools/importer/transformers/metadata.js

Fix #681 
Test URLs:
- After: https://681-default-prod-pages-no-aem-metadata--danaher-ls-aem--hlxsites.hlx.page/

removing metadata for default product page

---

fstab.yaml
tools/actions/convert/test/fixtures/blog-topics-template-converted.html
tools/actions/convert/test/fixtures/blog-topics-template.html
tools/importer/transformers/cardList.js
tools/importer/transformers/metadata.js

Related: #677
Test URLs:
- After: https://tag-pages--danaher-ls-aem--hlxsites.hlx.live/

feat: prep converter & fstab.yaml for blog topics

---

tools/actions/convert/test/fixtures/talk-to-expert-converted.html
tools/actions/convert/test/fixtures/talk-to-expert.html
tools/actions/convert/test/fixtures/workflow-carousel-converted.html
tools/importer/transformers/index.js
tools/importer/transformers/stats.js
tools/importer/transformers/workflowCarousel.js

Fix #785 
Test URLs:
- After: https://785-converter-for-stats-component--danaher-ls-aem--hlxsites.hlx.page/

785 [Solutions] Converter update for Stats Component

---

blocks/breadcrumb/breadcrumb.js

Fix #786
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/topics/cell-line-development
- After: https://breadcrumb-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/topics/cell-line-development

fix: breadcrumb for template pages

---

tools/actions/convert/test/fixtures/workflow-carousel-converted.html
tools/importer/transformers/workflowCarousel.js

Test URLs:
- After: https://fix-solutions-minor-converter-update--danaher-ls-aem--hlxsites.hlx.page/

Minor fix for workflow carousel converter

---

blocks/download/download.js
styles/styles.css

Fix #762 
Test URLs:
- After: https://762-ui-download-comp--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development

762 [Solutions] Block/UI download component

---

blocks/mini-teasers/mini-teasers.js

Fix #954 
Test URLs:
- After: https://954-mini-teasers-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/products
- After: https://954-mini-teasers-issue--danaher-ls-aem--hlxsites.hlx.page/us/en/new-homepage

954 [Products] Mini-teasers UI without description field

---

component-filters.json
tools/actions/convert/src/index.js
tools/actions/convert/test/pass-through/simple-converted.html
tools/actions/convert/test/pass-through/simple-pass-through.html
tools/actions/convert/test/pass-through/simple.html

- externalize image references so that the Helix Admin can generate image blobs
Fix #1083 
Test URLs:
- After: https://ue-images--danaher-ls-aem--hlxsites.hlx.page/

[UE] pass-through converter: rewrite images

---

component-definition.json
component-models.json

- add navigation title to the page metadata
Fix #1083 
Test URLs:
- After: https://ue-navtitle--danaher-ls-aem--hlxsites.hlx.page/

[UE] support navigation title

---

helix-query.yaml

- add navigation title to the index
Fix #1083 
Test URLs:
- After: https://ue-navtitle-index--danaher-ls-aem--hlxsites.hlx.page/

[UE] index navigation title

---

blocks/category-family/category-family.js
blocks/product-family/product-family.css
blocks/product-family/product-family.js
build-css.js
scripts/schema.js
styles/styles.css
tools/actions/convert/test/fixtures/product-category1-converted.html
tools/actions/convert/test/fixtures/product-category2-converted.html
tools/importer/transformers/coveoCategory.js

Fix #1172 
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/capillary-electrophoresis-systems
- After: https://1172-list-schema-family--danaher-ls-aem--hlxsites.hlx.page/us/en/products/capillary-electrophoresis-systems

1172 [SEO] Product list schema product family

---

paths.json

AEM has support for editing site metadata:
https://author-p93411-e849602.adobeaemcloud.com/content/danaher/ls/metadata.html
From now on site metadata should be handled this way.  Once validated, we can remove the metadata.json file in DAM at `/content/dam/danaher/franklin/metadata.json`.
Fix #1083 
Test URLs:
- After: https://ue-metadata--danaher-ls-aem--hlxsites.hlx.page/

[UE] use metadata created with the new UI 

---

paths.json

- adapt path mapping with .json extension
Test URLs:
- After: https://ue-metadata-2--danaher-ls-aem--hlxsites.hlx.page/

[UE] manage metadata from AEM UI

---

tools/actions/convert/test/fixtures/blog3-converted.html
tools/actions/convert/test/fixtures/product1-converted.html
tools/actions/convert/test/fixtures/product3-converted.html
tools/importer/transformers/util.js

Fix #1215 
Test URLs:
After: https://1215-embed-converter-update--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers

1215 Video Embed Converter Update

---

component-definition.json
component-filters.json
component-models.json
tools/actions/convert/src/index.js

Fix #1217 
Test URLs:
- After: https://1217-home-page-to-ue--danaher-ls-aem--hlxsites.hlx.page/

[UE] 1217 Updated for carousel for UE

---

component-models.json
tools/actions/convert/src/index.js

- remove work-around in component model for page meta data
- make the converter pass through the Blog pages
Fix #1083 
Test URLs:
- After: https://ue-blog-migration--danaher-ls-aem--hlxsites.hlx.page/

[UE] migrate blog pages

---

tools/actions/convert/src/index.js

- make the News pages skip the converter
Fix #1083 
Test URLs:
- After: https://ue-news-migration--danaher-ls-aem--hlxsites.hlx.page/

[UE] migrate News pages

---

blocks/product-hero/product-hero.js

Fix # 1311
Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica
- After: https://1311-products-title-metadata-fix--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica

1311 products title metadata fix

---

blocks/card-list/card-list.js
fstab.yaml
helix-query.yaml
tools/importer/transformers/cardList.js

Fix #<1322>
Test URLs:
- After: https://wsaw-hub--danaher-ls-aem--hlxsites.hlx.page/

Updated for wsaw hub page

---

helix-query.yaml
tools/actions/convert/test/fixtures/addtionalstyle-test-converted.html
tools/importer/transformers/cardList.js

Updated WSAW converter and index

---

tools/actions/convert/test/fixtures/addtionalstyle-test-converted.html
tools/importer/transformers/cardList.js

Updated converter

---

component-models.json
helix-query.yaml
models/_page-metadata.json

Adding new page properties attribute as "Category Title" which would be used for the categories title in products-index.json
Test URLs:
- After: https://em1-category-page-title-v22--danaher-ls-aem--hlxsites.hlx.page/

adding category title in page metadata
